## Notebook Summary

This notebook is dedicated to processing SNOMED CT data from `/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated`.

### Actions Taken:

1.  **Google Drive Connection:** Google Drive was successfully mounted.
2.  **SNOMED CT Data Processing:**
    *   The directory structure of the extracted SNOMED CT data was explored and listed.
    *   For various SNOMED CT RF2 files found in the `Full/Terminology`, `Full/Refset/Language`, `Full/Refset/Content`, `Full/Refset/Metadata`, `Snapshot/Terminology`, `Snapshot/Refset/Metadata`, `Snapshot/Refset/Language`, `Snapshot/Refset/Content` subdirectories, dedicated sections were created with a markdown overview, column descriptions, and a Python code cell to read and display the first 10 rows using `pd.read_csv` (configured for tab-separated files with a header, `sep='\t', header=0, on_bad_lines='skip', nrows=10`).
    *   **Updated SNOMED CT Processing**: All `.txt` files within the new SNOMED veterinary dataset located at `/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated` have been systematically processed. This includes generating markdown overviews, column descriptions, and Python code cells (to read the first 10 rows) for *every* `.txt` file found in the specified directory, following the hierarchical structure and ensuring all content is in English.

### Content:

The notebook contains markdown cells explaining the purpose of each SNOMED CT file and Python code cells displaying the first 10 rows of the files. This structure provides a quick overview of the datasets' content and structure.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Explore DIR Structure

In [4]:
import pandas as pd
import os

snomed_data_path = "/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated"
snomed_base_path = snomed_data_path # Corrected path

print(f"SNOMED CT Base Path: {snomed_base_path}")

SNOMED CT Base Path: /content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated

In [64]:
print(f"Listing directory structure for: {snomed_base_path}\n")
!ls -R {snomed_base_path}

Listing directory structure for: /content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated:
Full  Readme_en_20250930.txt  Snapshot

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full:
Refset	Terminology

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full/Refset:
Content  Language  Metadata

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full/Refset/Content:
der2_ciRefset_OrderedFull_VTS_20250930.txt
der2_cRefset_AssociationReferenceFull_VTS_20250930.txt
der2_cRefset_AttributeValueFull_VTS_20250930.txt
der2_Refset_simpleFull_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full/Refset/Language:
der2_cRefset_LanguageFull_en_VTS_20250930.txt
der2_cRefset_LanguageFull_es_VTS_20250930.txt
der2_cRefset_LanguageFull_it_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full/Refset/Metadata:
der2_ssRefset_ModuleDependencyfull_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Full/Terminology:
sct2_Concept_Full_VTS_20250930.txt
sct2_Description_Full_en_VTS_20250930.txt
sct2_Description_Full_es_VTS_20250930.txt
sct2_Description_Full_it_VTS_20250930.txt
sct2_Relationship_cd_Full_VTS_20250930.txt
sct2_Relationship_Full_VTS_20250930.txt
sct2_sRefset_OWLExpressionFull_VTS_20250930.txt
sct2_StatedRelationship_Full_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot:
Refset	Terminology

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot/Refset:
Content  Language  Metadata

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot/Refset/Content:
der2_ciRefset_OrderedSnapshot_VTS_20250930.txt
der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt
der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt
der2_Refset_simpleSnapshot_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot/Refset/Language:
der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt
der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt
der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot/Refset/Metadata:
der2_ssRefset_ModuleDependencySnapshot_VTS_20250930.txt

/content/drive/MyDrive/08_resolvers_general/SNOMED/SnomedCT_Release_VTS1000009_20250930_updated/Snapshot/Terminology:
sct2_Concept_Snapshot_VTS_20250930.txt
sct2_Description_Snapshot_en_VTS_20250930.txt
sct2_Description_Snapshot_es_VTS_20250930.txt
sct2_Description_Snapshot_it_VTS_20250930.txt
sct2_Relationship_Snapshot_VTS_20250930.txt
sct2_sRefset_OWLExpressionSnapshot_VTS_20250930.txt
sct2_StatedRelationship_Snapshot_VTS_20250930.txt

### Full/Refset/Content

## der2_ciRefset_OrderedFull_VTS_20250930.txt

### Overview
The `der2_ciRefset_OrderedFull` file represents an ordered reference set in the SNOMED CT Full Release. Ordered reference sets are used to maintain a specific sequence of components, which can be crucial for various applications, such as defining display order or complex rule definitions. This file contains the full history of ordered refset members.

### Column Descriptions
For ordered refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component that is a member of this refset.
*   **`mapTarget`**: The target value of the map.
*   **`mapGroup`**: The order group for the map entry.
*   **`mapPriority`**: The priority within the map group.
*   **`mapRule`**: A rule defining the mapping logic.
*   **`mapAdvice`**: Advice for the implementer regarding the map entry.
*   **`mapCorrelationId`**: Identifier for the correlation of the mapping.
*   **`mapCategoryId`**: Identifier for the category of the map.

In [65]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Content', 'der2_ciRefset_OrderedFull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_ciRefset_OrderedFull_VTS_20250930.txt'

Successfully loaded 'der2_ciRefset_OrderedFull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,linkedToId,order
0,9c2000c2-672f-11e2-87f0-bc8875af1040,20070221T160050Z,0,332351000009108,332801000009103,2022008,\N,0
1,9c208a55-672f-11e2-87f0-bc8875af1040,20070221T160108Z,0,332351000009108,332801000009103,71504001,\N,0
2,9c20c6da-672f-11e2-87f0-bc8875af1040,20070221T160131Z,0,332351000009108,332801000009103,131842007,\N,0
3,9c218ffa-672f-11e2-87f0-bc8875af1040,20070221T160200Z,0,332351000009108,332801000009103,406713005,\N,0
4,9c21906a-672f-11e2-87f0-bc8875af1040,20070221T160233Z,0,332351000009108,332801000009103,406716002,\N,0
5,9c219234-672f-11e2-87f0-bc8875af1040,20070221T160538Z,0,332351000009108,332801000009103,407324000,\N,0
6,9c21914f-672f-11e2-87f0-bc8875af1040,20070221T160606Z,0,332351000009108,332801000009103,407323006,\N,0
7,9c207018-672f-11e2-87f0-bc8875af1040,20070803T182433Z,0,332351000009108,332801000009103,60070007,\N,0
8,9c207e57-672f-11e2-87f0-bc8875af1040,20070803T182458Z,0,332351000009108,332801000009103,65767004,\N,0
9,9c219e45-672f-11e2-87f0-bc8875af1040,20080703T181733Z,0,332351000009108,332801000009103,1211000009100,\N,0

## der2_cRefset_AssociationReferenceFull_VTS_20250930.txt

### Overview
The `der2_cRefset_AssociationReferenceFull` file contains association reference set members in the SNOMED CT Full Release. Association reference sets are used to link concepts to other concepts or components using a specific type of association, such as 'same as' or 'part of'. This file contains the full history of association refset members.

### Column Descriptions
For association reference set files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the association applies.
*   **`targetComponentId`**: Identifier of the target component of the association.

In [66]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Content', 'der2_cRefset_AssociationReferenceFull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_AssociationReferenceFull_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_AssociationReferenceFull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,targetComponentId
0,007c1869-dc2a-11e5-8b35-9cc70ff59f3f,20160131T000000Z,1,332351000009108,900000000000526001,45011000009104,714084001
1,009f5204-77d9-4ac5-b436-1ea18edd4864,20250930T000000Z,0,332351000009108,900000000000524003,132460002,416516009
2,00be614e-fc5e-11e6-9c1d-00155df26e06,20170131T000000Z,1,332351000009108,900000000000526001,311751000009105,719186004
3,00f7c4b9-db07-11e5-8b35-9cc70ff59f3f,20160224T145218Z,1,332351000009108,900000000000526001,86329001,357561000009100
4,010ce330-a725-11e4-9c7a-a9c7ea3d7284,20150131T000000Z,1,332351000009108,900000000000526001,39531000009100,707509000
5,0138feb6-3b3b-4492-9a0b-62ad898caba7,20250930T000000Z,0,332351000009108,900000000000524003,409910000,416516009
6,02c431d3-dbf6-11ea-a5b1-00155df27801,20200731T000000Z,1,332351000009108,900000000000526001,321021000009109,866142007
7,0358a229-7b15-11e4-9047-a7efbad3f34b,20141203T175042Z,1,332351000009108,900000000000526001,341041000009102,333291000009101
8,0378d7f6-e7f5-11e6-baf3-00155df26e06,20170131T000000Z,1,332351000009108,900000000000526001,18650001,358191000009100
9,0390a935-6b3a-11eb-862b-00155df27801,20210131T000000Z,1,332351000009108,900000000000526001,309601000009102,879976004

## der2_cRefset_AttributeValueFull_VTS_20250930.txt

### Overview
The `der2_cRefset_AttributeValueFull` file contains attribute value reference set members in the SNOMED CT Full Release. These reference sets are used to assign specific values (attributes) to concepts, such as indicating a concept's status, clinical significance, or other properties. This file contains the full history of attribute value refset members.

### Column Descriptions
For attribute value refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the attribute value applies.
*   **`valueId`**: Identifier of the concept representing the assigned attribute value.

In [67]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Content', 'der2_cRefset_AttributeValueFull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_AttributeValueFull_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_AttributeValueFull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,valueId
0,00472f13-dc2a-11e5-8b35-9cc70ff59f3f,20160131T000000Z,1,332351000009108,900000000000489007,45011000009104,900000000000482003
1,00a22bdf-01f1-4d7f-b004-73fbdcc202dd,20250930T000000Z,1,332351000009108,900000000000490003,1002061000009115,900000000000495008
2,00a5a728-fc5e-11e6-9c1d-00155df26e06,20170131T000000Z,1,332351000009108,900000000000489007,311751000009105,900000000000482003
3,00ca3774-a725-11e4-9c7a-a9c7ea3d7284,20150131T000000Z,1,332351000009108,900000000000489007,39531000009100,900000000000482003
4,0173caf0-dbf6-11ea-a5b1-00155df27801,20200731T000000Z,1,332351000009108,900000000000489007,321021000009109,900000000000482003
5,0182fa44-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,331571000009104,900000000000487009
6,018a7896-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,327771000009100,900000000000487009
7,018c076b-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321561000009105,900000000000487009
8,018c0f5b-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321531000009103,900000000000487009
9,018eb8dd-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321441000009105,900000000000487009

## der2_Refset_simpleFull_VTS_20250930.txt

### Overview
The `der2_Refset_simpleFull` file contains members of a simple reference set in the SNOMED CT Full Release. Simple reference sets are used to group collections of SNOMED CT components (concepts, descriptions, or relationships) for various purposes, such as defining subsets of content or managing administrative lists. This file contains the full history of simple refset members.

### Column Descriptions
For simple refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component that is a member of this refset.

In [68]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Content', 'der2_Refset_simpleFull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_Refset_simpleFull_VTS_20250930.txt'

Successfully loaded 'der2_Refset_simpleFull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId
0,b528c090-1671-11e7-81fb-00155df26e06,20170801T211025Z,0,332351000009108,366551000009108,9446007
1,5ec3d2ce-1742-11e7-81fb-00155df26e06,20180908T011559Z,0,332351000009108,366551000009108,312770008
2,587b6615-19fa-11e7-81fb-00155df26e06,20180908T011742Z,0,332351000009108,366551000009108,302858007
3,b4e3bf6a-1671-11e7-81fb-00155df26e06,20190828T141800Z,0,332351000009108,366551000009108,358731000009102
4,b50024aa-1671-11e7-81fb-00155df26e06,20190828T141900Z,0,332351000009108,366551000009108,358601000009101
5,b5255ba7-1671-11e7-81fb-00155df26e06,20190828T141956Z,0,332351000009108,366551000009108,17541006
6,b4c5497a-1671-11e7-81fb-00155df26e06,20200124T161333Z,0,332351000009108,366551000009108,270906004
7,b478320a-1671-11e7-81fb-00155df26e06,20200205T170918Z,0,332351000009108,366551000009108,359011000009101
8,47a8b43e-1744-11e7-81fb-00155df26e06,20200922T203430Z,0,332351000009108,366551000009108,95728000
9,b4853747-1671-11e7-81fb-00155df26e06,20200922T203526Z,0,332351000009108,366551000009108,83270006

### Full/Refset/Language

## der2_cRefset_LanguageFull_en_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageFull_en` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (English in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the full history of English language refset members.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the English language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [69]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Language', 'der2_cRefset_LanguageFull_en_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageFull_en_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageFull_en_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,0002ddc5-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,213446019,900000000000548007
1,00039324-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,738448018,900000000000548007
2,000395db-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,2665886018,900000000000549004
3,000a0c98-fe99-11e6-9c1d-00155df26e06,20170301T162918Z,1,332351000009108,332501000009101,946001000009116,900000000000548007
4,000f1ce3-eeaa-11e4-9529-83e5f109579a,20150429T205714Z,1,332351000009108,332501000009101,942081000009110,900000000000548007
5,00136a06-fe99-11e6-9c1d-00155df26e06,20170301T162918Z,1,332351000009108,332501000009101,946011000009119,900000000000548007
6,0013bb35-a2cd-4919-8f65-0f2133f5f2c0,20250930T000000Z,1,332351000009108,332501000009101,940901000009115,900000000000548007
7,0013e017-eeaa-11e4-9529-83e5f109579a,20150429T205714Z,1,332351000009108,332501000009101,942091000009112,900000000000548007
8,0017efbf-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,64241015,900000000000548007
9,0018c31c-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,774031018,900000000000548007

## der2_cRefset_LanguageFull_es_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageFull_es` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (Spanish in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the full history of Spanish language refset members.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the Spanish language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [70]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Language', 'der2_cRefset_LanguageFull_es_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageFull_es_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageFull_es_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,06246cc3-15d9-11ed-a740-00155df27801,20220806T234217Z,1,332351000009108,362791000009105,779571000009118,900000000000548007
1,06246cc3-15d9-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,779571000009118,900000000000548007
2,0dc667d3-15da-11ed-a740-00155df27801,20220806T234939Z,1,332351000009108,362791000009105,987411000009118,900000000000548007
3,0e7344b8-144b-11ee-91e1-00155df27801,20230626T185829Z,1,332351000009108,362791000009105,1432011000009115,900000000000548007
4,1af17c7e-b3bf-11ed-b35f-00155df27801,20230223T211449Z,1,332351000009108,362791000009105,1429091000009118,900000000000548007
5,1c7ba4a0-15d9-11ed-a740-00155df27801,20220806T234254Z,1,332351000009108,362791000009105,985321000009113,900000000000548007
6,209201f8-15da-11ed-a740-00155df27801,20220806T235011Z,1,332351000009108,362791000009105,946051000009115,900000000000548007
7,209201f8-15da-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,946051000009115,900000000000548007
8,28dc83a4-083a-11f0-b894-00155df2780a,20250323T235713Z,1,332351000009108,362791000009105,1437271000009115,900000000000548007
9,3111ec67-15da-11ed-a740-00155df27801,20220806T235038Z,1,332351000009108,362791000009105,956161000009119,900000000000548007

## der2_cRefset_LanguageFull_it_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageFull_it` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (Italian in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the full history of Italian language refset members.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the Italian language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [71]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Language', 'der2_cRefset_LanguageFull_it_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageFull_it_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageFull_it_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,001643f1-0610-11ed-a740-00155df27801,20220717T213530Z,1,332351000009108,362551000009107,1424391000009115,900000000000548007
1,001a71ab-0610-11ed-a740-00155df27801,20220717T213530Z,1,332351000009108,362551000009107,1424401000009117,900000000000549004
2,038df577-060f-11ed-a740-00155df27801,20220717T212827Z,1,332351000009108,362551000009107,1424221000009110,900000000000548007
3,0392c71b-060f-11ed-a740-00155df27801,20220717T212827Z,1,332351000009108,362551000009107,1424231000009112,900000000000549004
4,04fe9cf7-0879-11ed-a740-00155df27801,20220720T231218Z,1,332351000009108,362551000009107,1424861000009116,900000000000548007
5,129184ac-ecad-4f03-ac94-f3a01a2f2134,20250930T000000Z,1,332351000009108,362551000009107,983361000009116,900000000000548007
6,14a02869-087d-11ed-a740-00155df27801,20220720T234122Z,1,332351000009108,362551000009107,1425121000009115,900000000000548007
7,14e6c055-b3c7-11ed-b35f-00155df27801,20230223T221154Z,1,332351000009108,362551000009107,1429141000009114,900000000000548007
8,15206c38-087c-11ed-a740-00155df27801,20220720T233414Z,1,332351000009108,362551000009107,1425051000009114,900000000000548007
9,178e0a67-060e-11ed-a740-00155df27801,20220717T212151Z,1,332351000009108,362551000009107,1424111000009112,900000000000548007

### Full/Refset/Metadata

## der2_ssRefset_ModuleDependencyfull_VTS_20250930.txt

### Overview
The `der2_ssRefset_ModuleDependencyfull` file contains module dependency reference set members in the SNOMED CT Full Release. This reference set defines the dependencies between different SNOMED CT modules, which is crucial for managing releases and ensuring consistency across various extensions and international releases. It specifies which modules depend on other modules.

### Column Descriptions
For module dependency refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs (i.e., the dependent module).
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the module that is dependent (e.g., a specific extension module).
*   **`targetComponentId`**: Identifier of the module that is depended upon (e.g., the International Release module).
*   **`sourceEffectiveTime`**: The effective time of the source module.
*   **`targetEffectiveTime`**: The effective time of the target module.

In [72]:
file_path = os.path.join(snomed_base_path, 'Full', 'Refset', 'Metadata', 'der2_ssRefset_ModuleDependencyfull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_ssRefset_ModuleDependencyfull_VTS_20250930.txt'

Successfully loaded 'der2_ssRefset_ModuleDependencyfull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,sourceEffectiveTime,targetEffectiveTime
0,0b81be96-35bf-11eb-a9d7-00155df27801,20170408T000000Z,1,332351000009108,900000000000534007,900000000000012004,20170408T000000Z,20180131T000000Z
1,0b81be96-35bf-11eb-a9d7-00155df27801,20170510T000000Z,1,332351000009108,900000000000534007,900000000000012004,20170510T000000Z,20180131T000000Z
2,0b81be96-35bf-11eb-a9d7-00155df27801,20171001T000000Z,1,332351000009108,900000000000534007,900000000000012004,20171001T000000Z,20170731T000000Z
3,0b81be96-35bf-11eb-a9d7-00155df27801,20180401T000000Z,1,332351000009108,900000000000534007,900000000000012004,20180401T000000Z,20180131T000000Z
4,0b81be96-35bf-11eb-a9d7-00155df27801,20181001T000000Z,1,332351000009108,900000000000534007,900000000000012004,20181001T000000Z,20180731T000000Z
5,0b81be96-35bf-11eb-a9d7-00155df27801,20190401T000000Z,1,332351000009108,900000000000534007,900000000000012004,20190401T000000Z,20190131T000000Z
6,0b81be96-35bf-11eb-a9d7-00155df27801,20191001T000000Z,1,332351000009108,900000000000534007,900000000000012004,20191001T000000Z,20190731T000000Z
7,0b81be96-35bf-11eb-a9d7-00155df27801,20191008T000000Z,1,332351000009108,900000000000534007,900000000000012004,20191008T000000Z,20190731T000000Z
8,0b81be96-35bf-11eb-a9d7-00155df27801,20200401T000000Z,1,332351000009108,900000000000534007,900000000000012004,20200401T000000Z,20200131T000000Z
9,0b81be96-35bf-11eb-a9d7-00155df27801,20201001T000000Z,1,332351000009108,900000000000534007,900000000000012004,20201001T000000Z,20200731T000000Z

### Full/Terminology

## sct2_Concept_Full_VTS_20250930.txt

### Overview
The `sct2_Concept_Full` file contains all SNOMED CT concepts in the Full Release. Concepts are the fundamental building blocks of SNOMED CT, representing clinical meanings. Each concept has a unique identifier and various attributes that define its characteristics and relationships to other concepts. This file includes the full historical record of concepts.

### Column Descriptions
For concept files, the columns typically include:
*   **`id`**: Unique identifier for the concept.
*   **`effectiveTime`**: Date and time when the concept version became active.
*   **`active`**: Indicates if the concept is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the concept belongs.
*   **`definitionStatusId`**: Identifier indicating the definition status of the concept (e.g., Primitive or Fully Defined).

In [73]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Concept_Full_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Concept_Full_VTS_20250930.txt'

Successfully loaded 'sct2_Concept_Full_VTS_20250930.txt'. Displaying the first 10 rows:

        id     effectiveTime  active         moduleId  definitionStatusId
0   300004  20210801T000000Z       1  332351000009108  900000000000074008
1   400003  20210801T000000Z       1  332351000009108  900000000000074008
2   507002  20210801T000000Z       1  332351000009108  900000000000074008
3   583000  20210801T000000Z       1  332351000009108  900000000000074008
4   606003  20210801T000000Z       1  332351000009108  900000000000074008
5   684003  20210801T000000Z       1  332351000009108  900000000000074008
6   797005  20210801T000000Z       1  332351000009108  900000000000074008
7   944009  20210801T000000Z       1  332351000009108  900000000000074008
8  1006005  20210801T000000Z       1  332351000009108  900000000000074008
9  1118004  20210801T000000Z       1  332351000009108  900000000000074008

## sct2_Description_Full_en_VTS_20250930.txt

### Overview
The `sct2_Description_Full_en` file contains all SNOMED CT descriptions for the English language in the Full Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the full historical record of English descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'en' for English).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [74]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Description_Full_en_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Full_en_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Full_en_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,967781000009117,20210128T231138Z,1,332351000009108,361911000009107,en,900000000000013009,Body condition score 1/9,900000000000448009
1,967771000009119,20210128T231138Z,1,332351000009108,361911000009107,en,900000000000003001,Body condition score 1/9 (finding),900000000000448009
2,11000009116,20070621T025335Z,1,332351000009108,31000009105,en,900000000000003001,Whole organ from digestive system (specimen),900000000000448009
3,21000009112,20060419T000000Z,1,332351000009108,31000009105,en,900000000000013009,Whole organ from digestive system,900000000000448009
4,31000009114,20070621T025335Z,1,332351000009108,41000009104,en,900000000000003001,Necropsy sample (specimen),900000000000448009
5,41000009115,20060419T000000Z,1,332351000009108,41000009104,en,900000000000013009,Necropsy sample,900000000000448009
6,51000009117,20070621T025335Z,1,332351000009108,51000009101,en,900000000000003001,Whole body specimen (specimen),900000000000448009
7,61000009119,20060419T000000Z,1,332351000009108,51000009101,en,900000000000013009,Whole body specimen,900000000000448009
8,71000009111,20070621T025335Z,1,332351000009108,61000009103,en,900000000000003001,Biofilter sample (specimen),900000000000448009
9,81000009113,20060419T000000Z,1,332351000009108,61000009103,en,900000000000013009,Biofilter sample,900000000000448009

## sct2_Description_Full_es_VTS_20250930.txt

### Overview
The `sct2_Description_Full_es` file contains all SNOMED CT descriptions for the Spanish language in the Full Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the full historical record of Spanish descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'es' for Spanish).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [75]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Description_Full_es_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Full_es_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Full_es_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,988601000009118,20220427T191909Z,1,332351000009108,26597004,es,900000000000013009,Hipoplasia del esmalte,900000000000448009
1,988611000009116,20220427T191909Z,1,332351000009108,70931000,es,900000000000013009,Lesión odontoclástica reabsortiva,900000000000017005
2,988621000009112,20220427T191909Z,1,332351000009108,234977009,es,900000000000013009,Erosión del esmalte,900000000000017005
3,988631000009114,20220427T191910Z,1,332351000009108,1141807004,es,900000000000013009,Costras en el párpado,900000000000017005
4,988641000009115,20220427T191910Z,1,332351000009108,1149073003,es,900000000000013009,Deficiencia de taurina,900000000000448009
5,988651000009117,20220427T191910Z,1,332351000009108,1149492007,es,900000000000013009,Disbiosis intestinal,900000000000448009
6,988661000009119,20220427T191910Z,1,332351000009108,1153476000,es,900000000000013009,Hiperalbuminemia,900000000000448009
7,988671000009111,20220427T191910Z,1,332351000009108,1153477009,es,900000000000013009,Hipoalbuminemia,900000000000448009
8,988681000009113,20220427T191910Z,1,332351000009108,1157018000,es,900000000000013009,Disminución de la saturación de oxígeno,900000000000017005
9,988691000009110,20220427T191910Z,1,332351000009108,33101000009102,es,900000000000013009,Edema submandibular,900000000000448009

## sct2_Description_Full_it_VTS_20250930.txt

### Overview
The `sct2_Description_Full_it` file contains all SNOMED CT descriptions for the Italian language in the Full Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the full historical record of Italian descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'it' for Italian).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [76]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Description_Full_it_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Full_it_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Full_it_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,970101000009119,20220119T195556Z,1,332351000009108,450005,it,900000000000013009,Stomatite ulcerosa,900000000000448009
1,970111000009117,20220119T195556Z,1,332351000009108,450005,it,900000000000013009,Stomatite ulcerativa,900000000000448009
2,970121000009113,20220119T195556Z,1,332351000009108,563001,it,900000000000013009,Nistagmo,900000000000448009
3,970131000009110,20220119T195556Z,1,332351000009108,815008,it,900000000000013009,Episclerite,900000000000448009
4,970141000009116,20220119T195556Z,1,332351000009108,849000,it,900000000000013009,Cataratta matura,900000000000448009
5,970151000009118,20220119T195556Z,1,332351000009108,1388004,it,900000000000013009,Alcalosi metabolica,900000000000448009
6,970161000009115,20220119T195556Z,1,332351000009108,1402001,it,900000000000013009,Paura,900000000000448009
7,970171000009112,20220119T195556Z,1,332351000009108,1482004,it,900000000000013009,Cisti della ghiandola di Meibomio,900000000000017005
8,970181000009114,20220119T195556Z,1,332351000009108,1482004,it,900000000000013009,Calazio,900000000000448009
9,970191000009111,20220119T195556Z,1,332351000009108,1845001,it,900000000000013009,Paraparesi,900000000000448009

## sct2_Relationship_cd_Full_VTS_20250930.txt

### Overview
The `sct2_Relationship_cd_Full` file contains SNOMED CT relationships in a 'compact' form within the Full Release. Relationships connect concepts to other concepts, forming the hierarchical and associative structure of SNOMED CT. These compact relationships represent historical versions of relationships, typically using integer IDs for efficiency. This file includes the full historical record of these compact relationships.

### Column Descriptions
For relationship files, the columns typically include:
*   **`id`**: Unique identifier for the relationship.
*   **`effectiveTime`**: Date and time when the relationship version became active.
*   **`active`**: Indicates if the relationship is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the relationship belongs.
*   **`sourceId`**: Identifier of the source concept of the relationship.
*   **`destinationId`**: Identifier of the destination concept of the relationship.
*   **`relationshipGroup`**: An integer indicating the relationship group for definitional relationships.
*   **`typeId`**: Identifier of the concept representing the type of relationship (e.g., 'Is a', 'Associated morphology').
*   **`characteristicTypeId`**: Identifier indicating the characteristic type of the relationship (e.g., 'Stated relationship', 'Inferred relationship').
*   **`modifierId`**: Identifier indicating the modifier of the relationship (e.g., 'Some', 'Qualification').

In [77]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Relationship_cd_Full_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Relationship_cd_Full_VTS_20250930.txt'

Successfully loaded 'sct2_Relationship_cd_Full_VTS_20250930.txt'. Displaying the first 10 rows:

Empty DataFrame
Columns: [id, effectiveTime, active, moduleId, sourceId, value, relationshipGroup, typeId, characteristicTypeId, modifierId]
Index: []

## sct2_Relationship_Full_VTS_20250930.txt

### Overview
The `sct2_Relationship_Full` file contains all SNOMED CT relationships in the Full Release. Relationships connect concepts to other concepts, forming the hierarchical and associative structure of SNOMED CT. This file includes the full historical record of relationships.

### Column Descriptions
For relationship files, the columns typically include:
*   **`id`**: Unique identifier for the relationship.
*   **`effectiveTime`**: Date and time when the relationship version became active.
*   **`active`**: Indicates if the relationship is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the relationship belongs.
*   **`sourceId`**: Identifier of the source concept of the relationship.
*   **`destinationId`**: Identifier of the destination concept of the relationship.
*   **`relationshipGroup`**: An integer indicating the relationship group for definitional relationships.
*   **`typeId`**: Identifier of the concept representing the type of relationship (e.g., 'Is a', 'Associated morphology').
*   **`characteristicTypeId`**: Identifier indicating the characteristic type of the relationship (e.g., 'Stated relationship', 'Inferred relationship').
*   **`modifierId`**: Identifier indicating the modifier of the relationship (e.g., 'Some', 'Qualification').

In [78]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_Relationship_Full_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Relationship_Full_VTS_20250930.txt'

Successfully loaded 'sct2_Relationship_Full_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,sourceId,destinationId,relationshipGroup,typeId,characteristicTypeId,modifierId
0,5115023,20210801T000000Z,1,332351000009108,10261003,80131009,0,116680003,900000000000011006,900000000000451002
1,18613025,20210801T000000Z,1,332351000009108,10544000,19078005,0,116680003,900000000000011006,900000000000451002
2,60794026,20210801T000000Z,1,332351000009108,11161001,74921000,0,116680003,900000000000011006,900000000000451002
3,69487022,20210801T000000Z,1,332351000009108,112490000,74921000,0,116680003,900000000000011006,900000000000451002
4,69517028,20210801T000000Z,1,332351000009108,112493003,2062007,0,116680003,900000000000011006,900000000000451002
5,89532028,20210801T000000Z,1,332351000009108,11477006,37453003,0,116680003,900000000000011006,900000000000451002
6,97865020,20220201T000000Z,1,332351000009108,279345006,80500007,0,116680003,900000000000011006,900000000000451002
7,148208029,20210801T000000Z,1,332351000009108,12091005,45625009,0,116680003,900000000000011006,900000000000451002
8,156478026,20210801T000000Z,1,332351000009108,12390000,23995009,0,116680003,900000000000011006,900000000000451002
9,156901027,20210801T000000Z,1,332351000009108,12407009,80131009,0,116680003,900000000000011006,900000000000451002

## sct2_sRefset_OWLExpressionFull_VTS_20250930.txt

### Overview
The `sct2_sRefset_OWLExpressionFull` file contains OWL Expression reference set members in the SNOMED CT Full Release. These reference sets allow for the inclusion of OWL (Web Ontology Language) expressions directly within SNOMED CT, enabling more complex logical definitions and interoperability with OWL-based tools and systems. This file contains the full history of OWL Expression refset members.

### Column Descriptions
For OWL Expression refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the OWL expression applies.
*   **`owlExpression`**: The OWL expression itself, typically in Manchester Syntax or Functional Syntax.

In [79]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_sRefset_OWLExpressionFull_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_sRefset_OWLExpressionFull_VTS_20250930.txt'

Successfully loaded 'sct2_sRefset_OWLExpressionFull_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleid,refsetid,referencedComponentId,owlExpression
0,00065381-1623-4bf5-b61f-7b33528121a0,20250930,1,332351000009108,733073007,152181000009105,SubClassOf(:152181000009105 :446265008)
1,0007e6c1-92a2-4aad-9d7a-791ac5259850,20250930,1,332351000009108,733073007,201561000009108,SubClassOf(:201561000009108 :98071000009105)
2,000891a3-3224-4a39-a29e-9b10e54e2699,20250930,1,332351000009108,733073007,34781000009106,SubClassOf(:34781000009106 ObjectIntersectionO...
3,00089238-a417-4cd0-8a94-38265b3ebbd9,20250930,1,332351000009108,733073007,297791000009101,SubClassOf(:297791000009101 :297781000009103)
4,000a8f58-feea-453b-9fff-a948f09e46da,20250930,1,332351000009108,733073007,266691000009109,SubClassOf(:266691000009109 :154371000009103)
5,000cbeed-fc9b-4111-92bd-147d3e810200,20250930,1,332351000009108,733073007,107961000009107,SubClassOf(:107961000009107 :107971000009103)
6,000cf8c4-9757-4546-8a6c-8703acf123c5,20250930,1,332351000009108,733073007,267451000009100,SubClassOf(:267451000009100 :154771000009102)
7,000f3af0-2cdd-43d7-a392-dbf561dd4f05,20250930,1,332351000009108,733073007,351441000009109,SubClassOf(:351441000009109 :343251000009105)
8,0011aa10-c89c-46f1-aa07-243894ea529f,20250930,1,332351000009108,733073007,133466001,SubClassOf(:133466001 :34618005)
9,0011b147-c6f2-4a9b-acf2-c751b1fa3be5,20250930,1,332351000009108,733073007,92061000009104,SubClassOf(:92061000009104 :107180002)

## sct2_StatedRelationship_Full_VTS_20250930.txt

### Overview
The `sct2_StatedRelationship_Full` file contains all SNOMED CT stated relationships in the Full Release. Stated relationships represent the explicit assertions made by clinical modelers and form the foundation of the SNOMED CT hierarchy and other essential relationships. This file includes the full historical record of stated relationships.

### Column Descriptions
For stated relationship files, the columns typically include:
*   **`id`**: Unique identifier for the relationship.
*   **`effectiveTime`**: Date and time when the relationship version became active.
*   **`active`**: Indicates if the relationship is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the relationship belongs.
*   **`sourceId`**: Identifier of the source concept of the relationship.
*   **`destinationId`**: Identifier of the destination concept of the relationship.
*   **`relationshipGroup`**: An integer indicating the relationship group for definitional relationships.
*   **`typeId`**: Identifier of the concept representing the type of relationship (e.g., 'Is a', 'Associated morphology').
*   **`characteristicTypeId`**: Identifier indicating the characteristic type of the relationship (e.g., 'Stated relationship', 'Inferred relationship').
*   **`modifierId`**: Identifier indicating the modifier of the relationship (e.g., 'Some', 'Qualification').

In [80]:
file_path = os.path.join(snomed_base_path, 'Full', 'Terminology', 'sct2_StatedRelationship_Full_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_StatedRelationship_Full_VTS_20250930.txt'

Successfully loaded 'sct2_StatedRelationship_Full_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,sourceId,destinationId,relationshipGroup,typeId,characteristicTypeId,modifierId
0,5115023,20210801,1,332351000009108,10261003,80131009,0,116680003,900000000000010007,900000000000451002
1,18613025,20210801,1,332351000009108,10544000,19078005,0,116680003,900000000000010007,900000000000451002
2,60794026,20210801,1,332351000009108,11161001,74921000,0,116680003,900000000000010007,900000000000451002
3,69487022,20210801,1,332351000009108,112490000,74921000,0,116680003,900000000000010007,900000000000451002
4,69517028,20210801,1,332351000009108,112493003,2062007,0,116680003,900000000000010007,900000000000451002
5,89532028,20210801,1,332351000009108,11477006,37453003,0,116680003,900000000000010007,900000000000451002
6,97865020,20220201,1,332351000009108,279345006,80500007,0,116680003,900000000000010007,900000000000451002
7,148208029,20210801,1,332351000009108,12091005,45625009,0,116680003,900000000000010007,900000000000451002
8,156478026,20210801,1,332351000009108,12390000,23995009,0,116680003,900000000000010007,900000000000451002
9,156901027,20210801,1,332351000009108,12407009,80131009,0,116680003,900000000000010007,900000000000451002

### Readme File

## Readme_en_20250930.txt

### Overview
This is a README file providing general information about the SNOMED CT release.

### Content
The content below is the full text of the README file.

In [81]:
file_path = os.path.join(snomed_base_path, 'Readme_en_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying its content:\n")
    print(content)
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'Readme_en_20250930.txt'

Successfully loaded 'Readme_en_20250930.txt'. Displaying its content:

Veterinary Extension of SNOMED CT(R):  September 30, 2025 Release - UPDATE

CORRECTION: This Updated set of release files contain a corrected rf2_description file.  There was an error in the original September release files that left out a significant number of descriptions.  All other files remain the same.

DISTRIBUTION UPDATE:   The Veterinary Extension of SNOMED is now available via SNOMED's Member Licensing and Distribution Services (https://mlds.ihtsdotools.org). In order to align our release with other extensions across the world, we will now be releasing a March 31 and September 30 release (compatible with the January 1 and July 1 International Release respectively). We will also continue to provide the release files on our website (https://vtsl.vetmed.vt.edu) for US entities via UMLS authentication. The Veterinary Edition of SNOMED CT (International Release plus Veterinary Extension content) is now available for browsing using the SNOMED Browser (https://browser.ihtsdotools.org).  Our own browser will continue to be available on our website as well.

Please note that due to the intricacies of the transition process, this initial release from the SNOMED platorm (and thus our release here) is compatible with the February 1, 2025 International release (rather than the July 1, 2025 Release).  We will resume a normal biennal pattern with  our next release in March, 2026.

Introduction

The Veterinary Extension to SNOMED CT is a formal extension to the SNOMED CT International release, maintained by the Veterinary Terminology Services Laboratory (VTSL) at the Virginia Maryland Regional College of Veterinary Medicine, Virginia Tech, Blacksburg, Va.  It contains content of veterinary importance as well as terms (descriptions) used by veterinarians that are not commonly used in human health.

Through the maintenance of the Veterinary Extension to SNOMED CT, VTSL provides content and services to the veterinary and public health communities.  It is our sincere belief that veterinary content should be curated by those with veterinary expertise and experience in terminology development.  With the January 2014 International Release of SNOMED CT, IHTSDO determined that content that did not apply to human medicine would no longer be considered within the scope of the International release.  All veterinary content was thereby retired from SNOMED CT and transferred to the Veterinary Extension to SNOMED CT.  All content that was retired from core, has been recreated as extension content and is found in the Veterinary Extension.  History associations are provided to guide migration from the core SCTIDs to the replacement extension SCTIDs.

The Veterinary Extension to SNOMED CT is distributed as tab delimited files, encoded in UTF-8, that conform to the IHTSDO RF2 specifications. This release is based on and compatible with the February 1, 2025 International Release of SNOMED CT.

File description

Please Note: These files contain the base EXTENSION terminology and all that is needed to display and use it.  It is fully integratable with International core content, and as such should be placed into the same tables with International core content to create a terminology that is all of International core plus Veterinary Content.

We DO NOT include reference sets created for individual organizations in this release file.  To obtain these reference sets, please contact us or the organization of interest.




    SnomedCT_Release_VTS1000009_20250930

	Full
            Refset
                Content
                    der2_ciRefset_OrderedFull_VTS_20250930.txt
                    der2_cRefset_AssociationReferenceFull_VTS_20250930.txt
                    der2_cRefset_AttributeValueFull_VTS_20250930.txt
                    der2_Refset_simpleFull_VTS_20250930.txt
                Language
                    der2_cRefset_LanguageFull_en_VTS_20250930.txt
                    der2_cRefset_LanguageFull_es_VTS_20250930.txt
                    der2_cRefset_LanguageFull_it_VTS_20250930.txt
                Metadata
                    der2_ssrefset_ModuleDependencyFull_VTS_20250930.txt
            Terminology
               	 	sct2_Concept_Full_VTS_20250930.txt
                	sct2_Description_Full_en_VTS_20250930.txt
               		sct2_Relationship_Full_VTS_20250930.txt
			sct2_OWLExpressionFull_VTS_20250930.txt
        Snapshot
            Refset
                Content
                    der2_ciRefset_OrderedSnapshot_VTS_20250930.txt
                    der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt
                    der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt
                    der2_Refset_simpleSnapshot_VTS_20250930.txt
                Language
                    der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt
                    der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt
                    der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt
                Metadata
                    der2_ssrefset_ModuleDependencySnapshot_VTS_20250930.txt
            Terminology
                sct2_Concept_Snapshot_VTS_20250930.txt
                sct2_Description_Snapshot_en_VTS_20250930.txt
                sct2_Relationship_Snapshot_VTS_20250930.txt
		sct2_OWLExpressionSnapshot_VTS_20250930.txt

    Readme_en_20250930.txt                                                  5 kilobytes

### Snapshot

### Snapshot/Refset/Content

## der2_ciRefset_OrderedSnapshot_VTS_20250930.txt

### Overview
The `der2_ciRefset_OrderedSnapshot` file represents an ordered reference set in the SNOMED CT Snapshot Release. Ordered reference sets are used to maintain a specific sequence of components, which can be crucial for various applications, such as defining display order or complex rule definitions. This file contains the current active members of the ordered refset.

### Column Descriptions
For ordered refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component that is a member of this refset.
*   **`mapTarget`**: The target value of the map.
*   **`mapGroup`**: The order group for the map entry.
*   **`mapPriority`**: The priority within the map group.
*   **`mapRule`**: A rule defining the mapping logic.
*   **`mapAdvice`**: Advice for the implementer regarding the map entry.
*   **`mapCorrelationId`**: Identifier for the correlation of the mapping.
*   **`mapCategoryId`**: Identifier for the category of the map.

In [82]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Content', 'der2_ciRefset_OrderedSnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_ciRefset_OrderedSnapshot_VTS_20250930.txt'

Successfully loaded 'der2_ciRefset_OrderedSnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,linkedToId,order
0,9c2000c2-672f-11e2-87f0-bc8875af1040,20070221T160050Z,0,332351000009108,332801000009103,2022008,\N,0
1,9c208a55-672f-11e2-87f0-bc8875af1040,20070221T160108Z,0,332351000009108,332801000009103,71504001,\N,0
2,9c20c6da-672f-11e2-87f0-bc8875af1040,20070221T160131Z,0,332351000009108,332801000009103,131842007,\N,0
3,9c218ffa-672f-11e2-87f0-bc8875af1040,20070221T160200Z,0,332351000009108,332801000009103,406713005,\N,0
4,9c21906a-672f-11e2-87f0-bc8875af1040,20070221T160233Z,0,332351000009108,332801000009103,406716002,\N,0
5,9c219234-672f-11e2-87f0-bc8875af1040,20070221T160538Z,0,332351000009108,332801000009103,407324000,\N,0
6,9c21914f-672f-11e2-87f0-bc8875af1040,20070221T160606Z,0,332351000009108,332801000009103,407323006,\N,0
7,9c207018-672f-11e2-87f0-bc8875af1040,20070803T182433Z,0,332351000009108,332801000009103,60070007,\N,0
8,9c207e57-672f-11e2-87f0-bc8875af1040,20070803T182458Z,0,332351000009108,332801000009103,65767004,\N,0
9,9c219e45-672f-11e2-87f0-bc8875af1040,20080703T181733Z,0,332351000009108,332801000009103,1211000009100,\N,0

## der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt

### Overview
The `der2_cRefset_AssociationReferenceSnapshot` file contains association reference set members in the SNOMED CT Snapshot Release. Association reference sets are used to link concepts to other concepts or components using a specific type of association, such as 'same as' or 'part of'. This file contains the current active members of association refsets.

### Column Descriptions
For association reference set files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the association applies.
*   **`targetComponentId`**: Identifier of the target component of the association.

In [83]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Content', 'der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_AssociationReferenceSnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,targetComponentId
0,007c1869-dc2a-11e5-8b35-9cc70ff59f3f,20160131T000000Z,1,332351000009108,900000000000526001,45011000009104,714084001
1,009f5204-77d9-4ac5-b436-1ea18edd4864,20250930T000000Z,0,332351000009108,900000000000524003,132460002,416516009
2,00be614e-fc5e-11e6-9c1d-00155df26e06,20170131T000000Z,1,332351000009108,900000000000526001,311751000009105,719186004
3,00f7c4b9-db07-11e5-8b35-9cc70ff59f3f,20160224T145218Z,1,332351000009108,900000000000526001,86329001,357561000009100
4,010ce330-a725-11e4-9c7a-a9c7ea3d7284,20150131T000000Z,1,332351000009108,900000000000526001,39531000009100,707509000
5,0138feb6-3b3b-4492-9a0b-62ad898caba7,20250930T000000Z,0,332351000009108,900000000000524003,409910000,416516009
6,02c431d3-dbf6-11ea-a5b1-00155df27801,20200731T000000Z,1,332351000009108,900000000000526001,321021000009109,866142007
7,0358a229-7b15-11e4-9047-a7efbad3f34b,20141203T175042Z,1,332351000009108,900000000000526001,341041000009102,333291000009101
8,0378d7f6-e7f5-11e6-baf3-00155df26e06,20170131T000000Z,1,332351000009108,900000000000526001,18650001,358191000009100
9,0390a935-6b3a-11eb-862b-00155df27801,20210131T000000Z,1,332351000009108,900000000000526001,309601000009102,879976004

## der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt

### Overview
The `der2_cRefset_AttributeValueSnapshot` file contains attribute value reference set members in the SNOMED CT Snapshot Release. These reference sets are used to assign specific values (attributes) to concepts, such as indicating a concept's status, clinical significance, or other properties. This file contains the current active members of attribute value refset.

### Column Descriptions
For attribute value refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the attribute value applies.
*   **`valueId`**: Identifier of the concept representing the assigned attribute value.

In [84]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Content', 'der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_AttributeValueSnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,valueId
0,00472f13-dc2a-11e5-8b35-9cc70ff59f3f,20160131T000000Z,1,332351000009108,900000000000489007,45011000009104,900000000000482003
1,00a22bdf-01f1-4d7f-b004-73fbdcc202dd,20250930T000000Z,1,332351000009108,900000000000490003,1002061000009115,900000000000495008
2,00a5a728-fc5e-11e6-9c1d-00155df26e06,20170131T000000Z,1,332351000009108,900000000000489007,311751000009105,900000000000482003
3,00ca3774-a725-11e4-9c7a-a9c7ea3d7284,20150131T000000Z,1,332351000009108,900000000000489007,39531000009100,900000000000482003
4,0173caf0-dbf6-11ea-a5b1-00155df27801,20200731T000000Z,1,332351000009108,900000000000489007,321021000009109,900000000000482003
5,0182fa44-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,331571000009104,900000000000487009
6,018a7896-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,327771000009100,900000000000487009
7,018c076b-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321561000009105,900000000000487009
8,018c0f5b-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321531000009103,900000000000487009
9,018eb8dd-db4a-11e5-8b35-9cc70ff59f3f,20160130T170000Z,1,332351000009108,900000000000489007,321441000009105,900000000000487009

## der2_Refset_simpleSnapshot_VTS_20250930.txt

### Overview
The `der2_Refset_simpleSnapshot` file contains members of a simple reference set in the SNOMED CT Snapshot Release. Simple reference sets are used to group collections of SNOMED CT components (concepts, descriptions, or relationships) for various purposes, such as defining subsets of content or managing administrative lists. This file contains the current active members of simple refsets.

### Column Descriptions
For simple refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component that is a member of this refset.

In [85]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Content', 'der2_Refset_simpleSnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_Refset_simpleSnapshot_VTS_20250930.txt'

Successfully loaded 'der2_Refset_simpleSnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId
0,b528c090-1671-11e7-81fb-00155df26e06,20170801T211025Z,0,332351000009108,366551000009108,9446007
1,5ec3d2ce-1742-11e7-81fb-00155df26e06,20180908T011559Z,0,332351000009108,366551000009108,312770008
2,587b6615-19fa-11e7-81fb-00155df26e06,20180908T011742Z,0,332351000009108,366551000009108,302858007
3,b4e3bf6a-1671-11e7-81fb-00155df26e06,20190828T141800Z,0,332351000009108,366551000009108,358731000009102
4,b50024aa-1671-11e7-81fb-00155df26e06,20190828T141900Z,0,332351000009108,366551000009108,358601000009101
5,b5255ba7-1671-11e7-81fb-00155df26e06,20190828T141956Z,0,332351000009108,366551000009108,17541006
6,b4c5497a-1671-11e7-81fb-00155df26e06,20200124T161333Z,0,332351000009108,366551000009108,270906004
7,b478320a-1671-11e7-81fb-00155df26e06,20200205T170918Z,0,332351000009108,366551000009108,359011000009101
8,47a8b43e-1744-11e7-81fb-00155df26e06,20200922T203430Z,0,332351000009108,366551000009108,95728000
9,b4853747-1671-11e7-81fb-00155df26e06,20200922T203526Z,0,332351000009108,366551000009108,83270006

### Snapshot/Refset/Language

## der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageSnapshot_en` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (English in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the current active members of English language refset.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the English language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [86]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Language', 'der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageSnapshot_en_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,0002ddc5-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,213446019,900000000000548007
1,00039324-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,738448018,900000000000548007
2,000395db-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,2665886018,900000000000549004
3,000a0c98-fe99-11e6-9c1d-00155df26e06,20170301T162918Z,1,332351000009108,332501000009101,946001000009116,900000000000548007
4,000f1ce3-eeaa-11e4-9529-83e5f109579a,20150429T205714Z,1,332351000009108,332501000009101,942081000009110,900000000000548007
5,00136a06-fe99-11e6-9c1d-00155df26e06,20170301T162918Z,1,332351000009108,332501000009101,946011000009119,900000000000548007
6,0013bb35-a2cd-4919-8f65-0f2133f5f2c0,20250930T000000Z,1,332351000009108,332501000009101,940901000009115,900000000000548007
7,0013e017-eeaa-11e4-9529-83e5f109579a,20150429T205714Z,1,332351000009108,332501000009101,942091000009112,900000000000548007
8,0017efbf-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,64241015,900000000000548007
9,0018c31c-f4a3-11eb-b3fc-00155df27801,20210801T000000Z,1,332351000009108,332501000009101,774031018,900000000000548007

## der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageSnapshot_es` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (Spanish in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the current active members of Spanish language refset.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the Spanish language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [87]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Language', 'der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageSnapshot_es_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,06246cc3-15d9-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,779571000009118,900000000000548007
1,0dc667d3-15da-11ed-a740-00155df27801,20220806T234939Z,1,332351000009108,362791000009105,987411000009118,900000000000548007
2,0e7344b8-144b-11ee-91e1-00155df27801,20230626T185829Z,1,332351000009108,362791000009105,1432011000009115,900000000000548007
3,1af17c7e-b3bf-11ed-b35f-00155df27801,20230223T211449Z,1,332351000009108,362791000009105,1429091000009118,900000000000548007
4,1c7ba4a0-15d9-11ed-a740-00155df27801,20220806T234254Z,1,332351000009108,362791000009105,985321000009113,900000000000548007
5,209201f8-15da-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,946051000009115,900000000000548007
6,28dc83a4-083a-11f0-b894-00155df2780a,20250323T235713Z,1,332351000009108,362791000009105,1437271000009115,900000000000548007
7,3111ec67-15da-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,956161000009119,900000000000548007
8,3216621d-b3b9-11ed-b35f-00155df27801,20230223T203230Z,1,332351000009108,362791000009105,1428931000009114,900000000000548007
9,3406b098-15d9-11ed-a740-00155df27801,20240224T234046Z,0,332351000009108,362791000009105,780011000009118,900000000000548007

## der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt

### Overview
The `der2_cRefset_LanguageSnapshot_it` file is a language reference set that associates concepts with their preferred terms and acceptable synonyms for a specific language (Italian in this case). It indicates which descriptions are preferred or acceptable for a given concept in a particular language. This file contains the current active members of Italian language refset.

### Column Descriptions
For language refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself (e.g., the Italian language refset).
*   **`referencedComponentId`**: Identifier of the description to which this refset entry applies.
*   **`acceptabilityId`**: Identifier indicating the acceptability of the description for the concept (e.g., 900000000000548007 for Preferred, 900000000000549004 for Acceptable).

In [88]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Language', 'der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt'

Successfully loaded 'der2_cRefset_LanguageSnapshot_it_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,acceptabilityId
0,001643f1-0610-11ed-a740-00155df27801,20220717T213530Z,1,332351000009108,362551000009107,1424391000009115,900000000000548007
1,001a71ab-0610-11ed-a740-00155df27801,20220717T213530Z,1,332351000009108,362551000009107,1424401000009117,900000000000549004
2,038df577-060f-11ed-a740-00155df27801,20220717T212827Z,1,332351000009108,362551000009107,1424221000009110,900000000000548007
3,0392c71b-060f-11ed-a740-00155df27801,20220717T212827Z,1,332351000009108,362551000009107,1424231000009112,900000000000549004
4,04fe9cf7-0879-11ed-a740-00155df27801,20220720T231218Z,1,332351000009108,362551000009107,1424861000009116,900000000000548007
5,129184ac-ecad-4f03-ac94-f3a01a2f2134,20250930T000000Z,1,332351000009108,362551000009107,983361000009116,900000000000548007
6,14a02869-087d-11ed-a740-00155df27801,20220720T234122Z,1,332351000009108,362551000009107,1425121000009115,900000000000548007
7,14e6c055-b3c7-11ed-b35f-00155df27801,20230223T221154Z,1,332351000009108,362551000009107,1429141000009114,900000000000548007
8,15206c38-087c-11ed-a740-00155df27801,20220720T233414Z,1,332351000009108,362551000009107,1425051000009114,900000000000548007
9,178e0a67-060e-11ed-a740-00155df27801,20220717T212151Z,1,332351000009108,362551000009107,1424111000009112,900000000000548007

### Snapshot/Refset/Metadata

## der2_ssRefset_ModuleDependencySnapshot_VTS_20250930.txt

### Overview
The `der2_ssRefset_ModuleDependencySnapshot` file contains module dependency reference set members in the SNOMED CT Snapshot Release. This reference set defines the dependencies between different SNOMED CT modules, which is crucial for managing releases and ensuring consistency across various extensions and international releases. It specifies which modules depend on other modules.

### Column Descriptions
For module dependency refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs (i.e., the dependent module).
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the module that is dependent (e.g., a specific extension module).
*   **`targetComponentId`**: Identifier of the module that is depended upon (e.g., the International Release module).
*   **`sourceEffectiveTime`**: The effective time of the source module.
*   **`targetEffectiveTime`**: The effective time of the target module.

In [89]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Refset', 'Metadata', 'der2_ssRefset_ModuleDependencySnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'der2_ssRefset_ModuleDependencySnapshot_VTS_20250930.txt'

Successfully loaded 'der2_ssRefset_ModuleDependencySnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,refsetId,referencedComponentId,sourceEffectiveTime,targetEffectiveTime
0,0b81be96-35bf-11eb-a9d7-00155df27801,20250401T000000Z,1,332351000009108,900000000000534007,900000000000012004,20250401T000000Z,20250201T000000Z
1,0b81c59b-35bf-11eb-a9d7-00155df27801,20250930T000000Z,1,332351000009108,900000000000534007,900000000000207008,20250930T000000Z,20250201T000000Z
2,1e28d4df-9027-42ee-9643-92eddd9ceabe,20250930T000000Z,1,332351000009108,900000000000534007,900000000000012004,20250930T000000Z,20250201T000000Z

### Snapshot/Terminology

## sct2_Concept_Snapshot_VTS_20250930.txt

### Overview
The `sct2_Concept_Snapshot` file contains all SNOMED CT concepts in the Snapshot Release. Concepts are the fundamental building blocks of SNOMED CT, representing clinical meanings. Each concept has a unique identifier and various attributes that define its characteristics and relationships to other concepts. This file includes the current active concepts.

### Column Descriptions
For concept files, the columns typically include:
*   **`id`**: Unique identifier for the concept.
*   **`effectiveTime`**: Date and time when the concept version became active.
*   **`active`**: Indicates if the concept is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the concept belongs.
*   **`definitionStatusId`**: Identifier indicating the definition status of the concept (e.g., Primitive or Fully Defined).

In [90]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_Concept_Snapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Concept_Snapshot_VTS_20250930.txt'

Successfully loaded 'sct2_Concept_Snapshot_VTS_20250930.txt'. Displaying the first 10 rows:

        id     effectiveTime  active         moduleId  definitionStatusId
0   300004  20210801T000000Z       1  332351000009108  900000000000074008
1   400003  20210801T000000Z       1  332351000009108  900000000000074008
2   507002  20210801T000000Z       1  332351000009108  900000000000074008
3   583000  20210801T000000Z       1  332351000009108  900000000000074008
4   606003  20210801T000000Z       1  332351000009108  900000000000074008
5   684003  20210801T000000Z       1  332351000009108  900000000000074008
6   797005  20210801T000000Z       1  332351000009108  900000000000074008
7   944009  20210801T000000Z       1  332351000009108  900000000000074008
8  1006005  20210801T000000Z       1  332351000009108  900000000000074008
9  1118004  20210801T000000Z       1  332351000009108  900000000000074008

## sct2_Description_Snapshot_en_VTS_20250930.txt

### Overview
The `sct2_Description_Snapshot_en` file contains all SNOMED CT descriptions for the English language in the Snapshot Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the current active English descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'en' for English).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [91]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_Description_Snapshot_en_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Snapshot_en_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Snapshot_en_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,967781000009117,20210128T231138Z,1,332351000009108,361911000009107,en,900000000000013009,Body condition score 1/9,900000000000448009
1,967771000009119,20210128T231138Z,1,332351000009108,361911000009107,en,900000000000003001,Body condition score 1/9 (finding),900000000000448009
2,11000009116,20070621T025335Z,1,332351000009108,31000009105,en,900000000000003001,Whole organ from digestive system (specimen),900000000000448009
3,21000009112,20060419T000000Z,1,332351000009108,31000009105,en,900000000000013009,Whole organ from digestive system,900000000000448009
4,31000009114,20070621T025335Z,1,332351000009108,41000009104,en,900000000000003001,Necropsy sample (specimen),900000000000448009
5,41000009115,20060419T000000Z,1,332351000009108,41000009104,en,900000000000013009,Necropsy sample,900000000000448009
6,51000009117,20070621T025335Z,1,332351000009108,51000009101,en,900000000000003001,Whole body specimen (specimen),900000000000448009
7,61000009119,20060419T000000Z,1,332351000009108,51000009101,en,900000000000013009,Whole body specimen,900000000000448009
8,71000009111,20070621T025335Z,1,332351000009108,61000009103,en,900000000000003001,Biofilter sample (specimen),900000000000448009
9,81000009113,20060419T000000Z,1,332351000009108,61000009103,en,900000000000013009,Biofilter sample,900000000000448009

## sct2_Description_Snapshot_es_VTS_20250930.txt

### Overview
The `sct2_Description_Snapshot_es` file contains all SNOMED CT descriptions for the Spanish language in the Snapshot Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the current active Spanish descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'es' for Spanish).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [92]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_Description_Snapshot_es_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Snapshot_es_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Snapshot_es_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,988601000009118,20220427T191909Z,1,332351000009108,26597004,es,900000000000013009,Hipoplasia del esmalte,900000000000448009
1,988611000009116,20220427T191909Z,1,332351000009108,70931000,es,900000000000013009,Lesión odontoclástica reabsortiva,900000000000017005
2,988621000009112,20220427T191909Z,1,332351000009108,234977009,es,900000000000013009,Erosión del esmalte,900000000000017005
3,988631000009114,20220427T191910Z,1,332351000009108,1141807004,es,900000000000013009,Costras en el párpado,900000000000017005
4,988641000009115,20220427T191910Z,1,332351000009108,1149073003,es,900000000000013009,Deficiencia de taurina,900000000000448009
5,988651000009117,20220427T191910Z,1,332351000009108,1149492007,es,900000000000013009,Disbiosis intestinal,900000000000448009
6,988661000009119,20220427T191910Z,1,332351000009108,1153476000,es,900000000000013009,Hiperalbuminemia,900000000000448009
7,988671000009111,20220427T191910Z,1,332351000009108,1153477009,es,900000000000013009,Hipoalbuminemia,900000000000448009
8,988681000009113,20220427T191910Z,1,332351000009108,1157018000,es,900000000000013009,Disminución de la saturación de oxígeno,900000000000017005
9,988691000009110,20220427T191910Z,1,332351000009108,33101000009102,es,900000000000013009,Edema submandibular,900000000000448009

## sct2_Description_Snapshot_it_VTS_20250930.txt

### Overview
The `sct2_Description_Snapshot_it` file contains all SNOMED CT descriptions for the Italian language in the Snapshot Release. Descriptions are human-readable phrases that represent a SNOMED CT concept. Each concept can have multiple descriptions, including fully specified names, preferred terms, and synonyms, each with a language code and acceptability status. This file includes the current active Italian descriptions.

### Column Descriptions
For description files, the columns typically include:
*   **`id`**: Unique identifier for the description.
*   **`effectiveTime`**: Date and time when the description version became active.
*   **`active`**: Indicates if the description is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the description belongs.
*   **`conceptId`**: Identifier of the concept to which this description applies.
*   **`languageCode`**: The language of the description (e.g., 'it' for Italian).
*   **`typeId`**: Identifier indicating the type of description (e.g., Fully Specified Name, Preferred Term, Synonym).
*   **`term`**: The human-readable text of the description.
*   **`caseSignificanceId`**: Identifier indicating the case significance of the term (e.g., case sensitive, case insensitive).

In [93]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_Description_Snapshot_it_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Description_Snapshot_it_VTS_20250930.txt'

Successfully loaded 'sct2_Description_Snapshot_it_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,conceptId,languageCode,typeId,term,caseSignificanceId
0,970101000009119,20220119T195556Z,1,332351000009108,450005,it,900000000000013009,Stomatite ulcerosa,900000000000448009
1,970111000009117,20220119T195556Z,1,332351000009108,450005,it,900000000000013009,Stomatite ulcerativa,900000000000448009
2,970121000009113,20220119T195556Z,1,332351000009108,563001,it,900000000000013009,Nistagmo,900000000000448009
3,970131000009110,20220119T195556Z,1,332351000009108,815008,it,900000000000013009,Episclerite,900000000000448009
4,970141000009116,20220119T195556Z,1,332351000009108,849000,it,900000000000013009,Cataratta matura,900000000000448009
5,970151000009118,20220119T195556Z,1,332351000009108,1388004,it,900000000000013009,Alcalosi metabolica,900000000000448009
6,970161000009115,20220119T195556Z,1,332351000009108,1402001,it,900000000000013009,Paura,900000000000448009
7,970171000009112,20220119T195556Z,1,332351000009108,1482004,it,900000000000013009,Cisti della ghiandola di Meibomio,900000000000017005
8,970181000009114,20220119T195556Z,1,332351000009108,1482004,it,900000000000013009,Calazio,900000000000448009
9,970191000009111,20220119T195556Z,1,332351000009108,1845001,it,900000000000013009,Paraparesi,900000000000448009

## sct2_Relationship_Snapshot_VTS_20250930.txt

### Overview
The `sct2_Relationship_Snapshot` file contains all SNOMED CT relationships in the Snapshot Release. Relationships connect concepts to other concepts, forming the hierarchical and associative structure of SNOMED CT. This file includes the current active relationships.

### Column Descriptions
For relationship files, the columns typically include:
*   **`id`**: Unique identifier for the relationship.
*   **`effectiveTime`**: Date and time when the relationship version became active.
*   **`active`**: Indicates if the relationship is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the relationship belongs.
*   **`sourceId`**: Identifier of the source concept of the relationship.
*   **`destinationId`**: Identifier of the destination concept of the relationship.
*   **`relationshipGroup`**: An integer indicating the relationship group for definitional relationships.
*   **`typeId`**: Identifier of the concept representing the type of relationship (e.g., 'Is a', 'Associated morphology').
*   **`characteristicTypeId`**: Identifier indicating the characteristic type of the relationship (e.g., 'Stated relationship', 'Inferred relationship').
*   **`modifierId`**: Identifier indicating the modifier of the relationship (e.g., 'Some', 'Qualification').

In [94]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_Relationship_Snapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_Relationship_Snapshot_VTS_20250930.txt'

Successfully loaded 'sct2_Relationship_Snapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,sourceId,destinationId,relationshipGroup,typeId,characteristicTypeId,modifierId
0,5115023,20210801T000000Z,1,332351000009108,10261003,80131009,0,116680003,900000000000011006,900000000000451002
1,18613025,20210801T000000Z,1,332351000009108,10544000,19078005,0,116680003,900000000000011006,900000000000451002
2,60794026,20210801T000000Z,1,332351000009108,11161001,74921000,0,116680003,900000000000011006,900000000000451002
3,69487022,20210801T000000Z,1,332351000009108,112490000,74921000,0,116680003,900000000000011006,900000000000451002
4,69517028,20210801T000000Z,1,332351000009108,112493003,2062007,0,116680003,900000000000011006,900000000000451002
5,89532028,20210801T000000Z,1,332351000009108,11477006,37453003,0,116680003,900000000000011006,900000000000451002
6,97865020,20220201T000000Z,1,332351000009108,279345006,80500007,0,116680003,900000000000011006,900000000000451002
7,148208029,20210801T000000Z,1,332351000009108,12091005,45625009,0,116680003,900000000000011006,900000000000451002
8,156478026,20210801T000000Z,1,332351000009108,12390000,23995009,0,116680003,900000000000011006,900000000000451002
9,156901027,20210801T000000Z,1,332351000009108,12407009,80131009,0,116680003,900000000000011006,900000000000451002

## sct2_sRefset_OWLExpressionSnapshot_VTS_20250930.txt

### Overview
The `sct2_sRefset_OWLExpressionSnapshot` file contains OWL Expression reference set members in the SNOMED CT Snapshot Release. These reference sets allow for the inclusion of OWL (Web Ontology Language) expressions directly within SNOMED CT, enabling more complex logical definitions and interoperability with OWL-based tools and systems. This file contains the current active OWL Expression refset members.

### Column Descriptions
For OWL Expression refset files, the columns typically include:
*   **`id`**: Unique identifier for the refset member.
*   **`effectiveTime`**: Date and time when the component version became active.
*   **`active`**: Indicates if the refset member is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the component belongs.
*   **`refsetId`**: Identifier of the reference set itself.
*   **`referencedComponentId`**: Identifier of the SNOMED CT component to which the OWL expression applies.
*   **`owlExpression`**: The OWL expression itself, typically in Manchester Syntax or Functional Syntax.

In [95]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_sRefset_OWLExpressionSnapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_sRefset_OWLExpressionSnapshot_VTS_20250930.txt'

Successfully loaded 'sct2_sRefset_OWLExpressionSnapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleid,refsetid,referencedComponentId,owlExpression
0,00065381-1623-4bf5-b61f-7b33528121a0,20250930,1,332351000009108,733073007,152181000009105,SubClassOf(:152181000009105 :446265008)
1,0007e6c1-92a2-4aad-9d7a-791ac5259850,20250930,1,332351000009108,733073007,201561000009108,SubClassOf(:201561000009108 :98071000009105)
2,000891a3-3224-4a39-a29e-9b10e54e2699,20250930,1,332351000009108,733073007,34781000009106,SubClassOf(:34781000009106 ObjectIntersectionO...
3,00089238-a417-4cd0-8a94-38265b3ebbd9,20250930,1,332351000009108,733073007,297791000009101,SubClassOf(:297791000009101 :297781000009103)
4,000a8f58-feea-453b-9fff-a948f09e46da,20250930,1,332351000009108,733073007,266691000009109,SubClassOf(:266691000009109 :154371000009103)
5,000cbeed-fc9b-4111-92bd-147d3e810200,20250930,1,332351000009108,733073007,107961000009107,SubClassOf(:107961000009107 :107971000009103)
6,000cf8c4-9757-4546-8a6c-8703acf123c5,20250930,1,332351000009108,733073007,267451000009100,SubClassOf(:267451000009100 :154771000009102)
7,000f3af0-2cdd-43d7-a392-dbf561dd4f05,20250930,1,332351000009108,733073007,351441000009109,SubClassOf(:351441000009109 :343251000009105)
8,0011aa10-c89c-46f1-aa07-243894ea529f,20250930,1,332351000009108,733073007,133466001,SubClassOf(:133466001 :34618005)
9,0011b147-c6f2-4a9b-acf2-c751b1fa3be5,20250930,1,332351000009108,733073007,92061000009104,SubClassOf(:92061000009104 :107180002)

## sct2_StatedRelationship_Snapshot_VTS_20250930.txt

### Overview
The `sct2_StatedRelationship_Snapshot` file contains all SNOMED CT stated relationships in the Snapshot Release. Stated relationships represent the explicit assertions made by clinical modelers and form the foundation of the SNOMED CT hierarchy and other essential relationships. This file includes the current active stated relationships.

### Column Descriptions
For stated relationship files, the columns typically include:
*   **`id`**: Unique identifier for the relationship.
*   **`effectiveTime`**: Date and time when the relationship version became active.
*   **`active`**: Indicates if the relationship is active (1) or inactive (0).
*   **`moduleId`**: Identifier of the module to which the relationship belongs.
*   **`sourceId`**: Identifier of the source concept of the relationship.
*   **`destinationId`**: Identifier of the destination concept of the relationship.
*   **`relationshipGroup`**: An integer indicating the relationship group for definitional relationships.
*   **`typeId`**: Identifier of the concept representing the type of relationship (e.g., 'Is a', 'Associated morphology').
*   **`characteristicTypeId`**: Identifier indicating the characteristic type of the relationship (e.g., 'Stated relationship', 'Inferred relationship').
*   **`modifierId`**: Identifier indicating the modifier of the relationship (e.g., 'Some', 'Qualification').

In [96]:
file_path = os.path.join(snomed_base_path, 'Snapshot', 'Terminology', 'sct2_StatedRelationship_Snapshot_VTS_20250930.txt')

print(f"### Reading '{os.path.basename(file_path)}'\n")
try:
    # SNOMED CT RF2 files are typically tab-separated and have a header row.
    df = pd.read_csv(file_path, sep='\t', header=0, on_bad_lines='skip', nrows=10)
    print(f"Successfully loaded '{os.path.basename(file_path)}'. Displaying the first 10 rows:")
    display(df.head(10))
except Exception as e:
    print(f"Error reading '{os.path.basename(file_path)}': {e}")

### Reading 'sct2_StatedRelationship_Snapshot_VTS_20250930.txt'

Successfully loaded 'sct2_StatedRelationship_Snapshot_VTS_20250930.txt'. Displaying the first 10 rows:

,id,effectiveTime,active,moduleId,sourceId,destinationId,relationshipGroup,typeId,characteristicTypeId,modifierId
0,5115023,20210801,1,332351000009108,10261003,80131009,0,116680003,900000000000010007,900000000000451002
1,18613025,20210801,1,332351000009108,10544000,19078005,0,116680003,900000000000010007,900000000000451002
2,60794026,20210801,1,332351000009108,11161001,74921000,0,116680003,900000000000010007,900000000000451002
3,69487022,20210801,1,332351000009108,112490000,74921000,0,116680003,900000000000010007,900000000000451002
4,69517028,20210801,1,332351000009108,112493003,2062007,0,116680003,900000000000010007,900000000000451002
5,89532028,20210801,1,332351000009108,11477006,37453003,0,116680003,900000000000010007,900000000000451002
6,97865020,20220201,1,332351000009108,279345006,80500007,0,116680003,900000000000010007,900000000000451002
7,148208029,20210801,1,332351000009108,12091005,45625009,0,116680003,900000000000010007,900000000000451002
8,156478026,20210801,1,332351000009108,12390000,23995009,0,116680003,900000000000010007,900000000000451002
9,156901027,20210801,1,332351000009108,12407009,80131009,0,116680003,900000000000010007,900000000000451002