# UMLS 2025AB Parser - Handling GZIP and Split Files

This notebook processes UMLS data from gzipped and split RRF files.

# Local Download

- Download latest UMLS data from S3 to local.

- Use 7-zip for extracting the following files.
   - 2025ab-1-meta.nlm
   - 2025ab-2-meta.nlm
   - 2025ab-otherks.nlm

- Finally, 2025AB folder will be built and in it, there will be following folders;
   - LEX
   - META
   - NET

- Move 2025AB folder to Google Drive.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os

meta_folder = '/content/drive/MyDrive/UMLS/2025AB/META'
net_folder = '/content/drive/MyDrive/UMLS/2025AB/NET'

print(f"Files in {meta_folder}:")
if os.path.exists(meta_folder):
    for item in os.listdir(meta_folder):
        print(f"  {item}")
else:
    print(f"  Folder not found: {meta_folder}")

print(f"\nFiles in {net_folder}:")
if os.path.exists(net_folder):
    for item in os.listdir(net_folder):
        print(f"  {item}")
else:
    print(f"  Folder not found: {net_folder}")

Files in /content/drive/MyDrive/UMLS/2025AB/META:
  MRHIER.RRF.aa.gz
  MRREL.RRF.ac.gz
  MRXW_DUT.RRF.gz
  MRCONSO.RRF.ac.gz
  MRXW_ENG.RRF.ab.gz
  MRDEF.RRF.gz
  MRXW_SWE.RRF.gz
  MRCONSO.RRF.ab.gz
  MRXW_ENG.RRF.aa.gz
  MRXW_ITA.RRF.gz
  MRXNW_ENG.RRF.aa.gz
  MRXW_KOR.RRF.gz
  MRXW_FRE.RRF.gz
  MRXW_FIN.RRF.gz
  MRSAB.RRF.gz
  MRXW_NOR.RRF.gz
  MRCOLS.RRF.gz
  MRHIER.RRF.ab.gz
  MRSTY.RRF.gz
  MRXW_LIT.RRF.gz
  MRXW_ARA.RRF.gz
  MRXW_UKR.RRF.gz
  AMBIGSUI.RRF.gz
  MRXNS_ENG.RRF.ab.gz
  MRAUI.RRF.gz
  MRSAT.RRF.ab.gz
  MRREL.RRF.ab.gz
  MRHIER.RRF.ac.gz
  MRSAT.RRF.af.gz
  MRXW_SPA.RRF.gz
  MRXW_CHI.RRF.gz
  MRXW_CZE.RRF.gz
  MRSAT.RRF.ae.gz
  MRSAT.RRF.ac.gz
  AMBIGLUI.RRF.gz
  MRXW_HEB.RRF.gz
  MRHIER.RRF.ae.gz
  MRXNW_ENG.RRF.ab.gz
  MRSAT.RRF.ad.gz
  MRXNS_ENG.RRF.aa.gz
  MRCONSO.RRF.aa.gz
  MRXW_EST.RRF.gz
  MRXW_TUR.RRF.gz
  MRXW_HUN.RRF.gz
  MRSMAP.RRF.gz
  MRFILES.RRF.gz
  MRXW_LAV.RRF.gz
  MRMAP.RRF.gz
  MRXW_RUS.RRF.gz
  MRSAT.RRF.aa.gz
  MRXW_GER.RRF.gz
  MRXW_BAQ.RRF.gz
  MRDOC.RRF.gz
  MRREL.RRF.ae.gz
  MRCUI.RRF.gz
  MRREL.RRF.ad.gz
  MRXW_POR.RRF.gz
  MRXW_POL.RRF.gz
  MRRANK.RRF.gz
  MRXW_ISL.RRF.gz
  MRREL.RRF.aa.gz
  MRXW_DAN.RRF.gz
  MRXW_SCR.RRF.gz
  MRHIER.RRF.ad.gz
  MRXW_GRE.RRF.gz
  MRXW_JPN.RRF.gz

Files in /content/drive/MyDrive/UMLS/2025AB/NET:
  SRSTRE1
  SRDEF
  SRFLD
  SRFIL
  SRSTRE2
  SRSTR
  SU

# META Folder

In [4]:
import os
import gzip
import re
from collections import defaultdict

source_folder = '/content/drive/MyDrive/UMLS/2025AB/META'
destination_folder = '/content/drive/MyDrive/UMLS/2025RRFs'

# Create the destination folder if it doesn't exist
os.makedirs(destination_folder, exist_ok=True)

print(f"Source folder: {source_folder}")
print(f"Destination folder: {destination_folder}")

rrf_files_to_process = defaultdict(list)

# Group gzipped files by their base RRF name
for filename in os.listdir(source_folder):
    if filename.endswith('.gz'):
        # Use regex to find the base RRF name
        # This handles both MRCONSO.RRF.aa.gz and MRDEF.RRF.gz
        # Updated regex to correctly capture the base RRF name
        match = re.match(r"([A-Z_]+\.RRF)(?:\.[a-z]{2})?\.gz$", filename)
        if match:
            base_rrf_name = match.group(1)
            full_path = os.path.join(source_folder, filename)
            rrf_files_to_process[base_rrf_name].append(full_path)
        else:
            print(f"Warning: Could not parse base RRF name for {filename}. Skipping.")

print(f"\nFound {len(rrf_files_to_process)} unique RRF groups to extract.")

# Process each group of RRF files
for base_rrf_name, gzipped_parts in rrf_files_to_process.items():
    output_rrf_path = os.path.join(destination_folder, base_rrf_name)

    # Sort the parts to ensure correct order for concatenation (e.g., .aa, .ab, .ac)
    gzipped_parts.sort()

    print(f"\nExtracting and concatenating {len(gzipped_parts)} part(s) for '{base_rrf_name}' to '{output_rrf_path}'...")

    try:
        # Open the output RRF file in text write mode with UTF-8 encoding
        with open(output_rrf_path, 'wt', encoding='utf-8') as outfile:
            for part_file_path in gzipped_parts:
                print(f"  - Processing: {os.path.basename(part_file_path)}")
                # Open each gzipped part in text read mode with UTF-8 encoding
                with gzip.open(part_file_path, 'rt', encoding='utf-8') as infile:
                    outfile.write(infile.read())
        print(f"✅ Successfully extracted and concatenated '{base_rrf_name}'")
    except Exception as e:
        print(f"❌ Error processing '{base_rrf_name}': {e}")

print("\nExtraction process complete.")

Source folder: /content/drive/MyDrive/UMLS/2025AB/META
Destination folder: /content/drive/MyDrive/UMLS/2025RRFs

Found 48 unique RRF groups to extract.

Extracting and concatenating 5 part(s) for 'MRHIER.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRHIER.RRF'...
  - Processing: MRHIER.RRF.aa.gz
  - Processing: MRHIER.RRF.ab.gz
  - Processing: MRHIER.RRF.ac.gz
  - Processing: MRHIER.RRF.ad.gz
  - Processing: MRHIER.RRF.ae.gz
✅ Successfully extracted and concatenated 'MRHIER.RRF'

Extracting and concatenating 5 part(s) for 'MRREL.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRREL.RRF'...
  - Processing: MRREL.RRF.aa.gz
  - Processing: MRREL.RRF.ab.gz
  - Processing: MRREL.RRF.ac.gz
  - Processing: MRREL.RRF.ad.gz
  - Processing: MRREL.RRF.ae.gz
✅ Successfully extracted and concatenated 'MRREL.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_DUT.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_DUT.RRF'...
  - Processing: MRXW_DUT.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_DUT.RRF'

Extracting and concatenating 3 part(s) for 'MRCONSO.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRCONSO.RRF'...
  - Processing: MRCONSO.RRF.aa.gz
  - Processing: MRCONSO.RRF.ab.gz
  - Processing: MRCONSO.RRF.ac.gz
✅ Successfully extracted and concatenated 'MRCONSO.RRF'

Extracting and concatenating 2 part(s) for 'MRXW_ENG.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ENG.RRF'...
  - Processing: MRXW_ENG.RRF.aa.gz
  - Processing: MRXW_ENG.RRF.ab.gz
✅ Successfully extracted and concatenated 'MRXW_ENG.RRF'

Extracting and concatenating 1 part(s) for 'MRDEF.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRDEF.RRF'...
  - Processing: MRDEF.RRF.gz
✅ Successfully extracted and concatenated 'MRDEF.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_SWE.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SWE.RRF'...
  - Processing: MRXW_SWE.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_SWE.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_ITA.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ITA.RRF'...
  - Processing: MRXW_ITA.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_ITA.RRF'

Extracting and concatenating 2 part(s) for 'MRXNW_ENG.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXNW_ENG.RRF'...
  - Processing: MRXNW_ENG.RRF.aa.gz
  - Processing: MRXNW_ENG.RRF.ab.gz
✅ Successfully extracted and concatenated 'MRXNW_ENG.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_KOR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_KOR.RRF'...
  - Processing: MRXW_KOR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_KOR.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_FRE.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_FRE.RRF'...
  - Processing: MRXW_FRE.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_FRE.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_FIN.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_FIN.RRF'...
  - Processing: MRXW_FIN.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_FIN.RRF'

Extracting and concatenating 1 part(s) for 'MRSAB.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRSAB.RRF'...
  - Processing: MRSAB.RRF.gz
✅ Successfully extracted and concatenated 'MRSAB.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_NOR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_NOR.RRF'...
  - Processing: MRXW_NOR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_NOR.RRF'

Extracting and concatenating 1 part(s) for 'MRCOLS.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRCOLS.RRF'...
  - Processing: MRCOLS.RRF.gz
✅ Successfully extracted and concatenated 'MRCOLS.RRF'

Extracting and concatenating 1 part(s) for 'MRSTY.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRSTY.RRF'...
  - Processing: MRSTY.RRF.gz
✅ Successfully extracted and concatenated 'MRSTY.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_LIT.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_LIT.RRF'...
  - Processing: MRXW_LIT.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_LIT.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_ARA.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ARA.RRF'...
  - Processing: MRXW_ARA.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_ARA.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_UKR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_UKR.RRF'...
  - Processing: MRXW_UKR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_UKR.RRF'

Extracting and concatenating 1 part(s) for 'AMBIGSUI.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/AMBIGSUI.RRF'...
  - Processing: AMBIGSUI.RRF.gz
✅ Successfully extracted and concatenated 'AMBIGSUI.RRF'

Extracting and concatenating 2 part(s) for 'MRXNS_ENG.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXNS_ENG.RRF'...
  - Processing: MRXNS_ENG.RRF.aa.gz
  - Processing: MRXNS_ENG.RRF.ab.gz
✅ Successfully extracted and concatenated 'MRXNS_ENG.RRF'

Extracting and concatenating 1 part(s) for 'MRAUI.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRAUI.RRF'...
  - Processing: MRAUI.RRF.gz
✅ Successfully extracted and concatenated 'MRAUI.RRF'

Extracting and concatenating 6 part(s) for 'MRSAT.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRSAT.RRF'...
  - Processing: MRSAT.RRF.aa.gz
  - Processing: MRSAT.RRF.ab.gz
  - Processing: MRSAT.RRF.ac.gz
  - Processing: MRSAT.RRF.ad.gz
  - Processing: MRSAT.RRF.ae.gz
  - Processing: MRSAT.RRF.af.gz
✅ Successfully extracted and concatenated 'MRSAT.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_SPA.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SPA.RRF'...
  - Processing: MRXW_SPA.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_SPA.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_CHI.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_CHI.RRF'...
  - Processing: MRXW_CHI.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_CHI.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_CZE.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_CZE.RRF'...
  - Processing: MRXW_CZE.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_CZE.RRF'

Extracting and concatenating 1 part(s) for 'AMBIGLUI.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/AMBIGLUI.RRF'...
  - Processing: AMBIGLUI.RRF.gz
✅ Successfully extracted and concatenated 'AMBIGLUI.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_HEB.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_HEB.RRF'...
  - Processing: MRXW_HEB.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_HEB.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_EST.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_EST.RRF'...
  - Processing: MRXW_EST.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_EST.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_TUR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_TUR.RRF'...
  - Processing: MRXW_TUR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_TUR.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_HUN.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_HUN.RRF'...
  - Processing: MRXW_HUN.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_HUN.RRF'

Extracting and concatenating 1 part(s) for 'MRSMAP.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRSMAP.RRF'...
  - Processing: MRSMAP.RRF.gz
✅ Successfully extracted and concatenated 'MRSMAP.RRF'

Extracting and concatenating 1 part(s) for 'MRFILES.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRFILES.RRF'...
  - Processing: MRFILES.RRF.gz
✅ Successfully extracted and concatenated 'MRFILES.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_LAV.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_LAV.RRF'...
  - Processing: MRXW_LAV.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_LAV.RRF'

Extracting and concatenating 1 part(s) for 'MRMAP.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRMAP.RRF'...
  - Processing: MRMAP.RRF.gz
✅ Successfully extracted and concatenated 'MRMAP.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_RUS.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_RUS.RRF'...
  - Processing: MRXW_RUS.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_RUS.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_GER.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_GER.RRF'...
  - Processing: MRXW_GER.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_GER.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_BAQ.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_BAQ.RRF'...
  - Processing: MRXW_BAQ.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_BAQ.RRF'

Extracting and concatenating 1 part(s) for 'MRDOC.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRDOC.RRF'...
  - Processing: MRDOC.RRF.gz
✅ Successfully extracted and concatenated 'MRDOC.RRF'

Extracting and concatenating 1 part(s) for 'MRCUI.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRCUI.RRF'...
  - Processing: MRCUI.RRF.gz
✅ Successfully extracted and concatenated 'MRCUI.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_POR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_POR.RRF'...
  - Processing: MRXW_POR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_POR.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_POL.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_POL.RRF'...
  - Processing: MRXW_POL.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_POL.RRF'

Extracting and concatenating 1 part(s) for 'MRRANK.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRRANK.RRF'...
  - Processing: MRRANK.RRF.gz
✅ Successfully extracted and concatenated 'MRRANK.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_ISL.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ISL.RRF'...
  - Processing: MRXW_ISL.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_ISL.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_DAN.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_DAN.RRF'...
  - Processing: MRXW_DAN.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_DAN.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_SCR.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SCR.RRF'...
  - Processing: MRXW_SCR.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_SCR.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_GRE.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_GRE.RRF'...
  - Processing: MRXW_GRE.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_GRE.RRF'

Extracting and concatenating 1 part(s) for 'MRXW_JPN.RRF' to '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_JPN.RRF'...
  - Processing: MRXW_JPN.RRF.gz
✅ Successfully extracted and concatenated 'MRXW_JPN.RRF'

Extraction process complete.

## RRF Reader - helper function

In [9]:
rrf_column_definitions = {
    'AMBIGLUI.RRF': ['LUI', 'CUI', 'VER'],
    'AMBIGSUI.RRF': ['SUI', 'CUI', 'VER'],
    'MRAUI.RRF': ['AUI', 'CUI', 'LUI', 'SUI', 'SAP', 'VER'],
    'MRCUI.RRF': ['CUI1', 'CUI2', 'VCUI'],
    'MRCOLS.RRF': ['COL', 'COL_NM', 'FLG', 'FBG', 'FBL', 'DIR_NM', 'FIL', 'MIN_LEN', 'MAX_LEN', 'DATA_TY'],
    'MRCONSO.RRF': ['CUI', 'LAT', 'TS', 'LUI', 'STT', 'SUI', 'ISPREF', 'AUI', 'SAUI', 'SCUI', 'SDUI', 'SAB', 'TTY', 'CODE', 'STR', 'SRL', 'SUPPRESS', 'CVF'],
    'MRDEF.RRF': ['CUI', 'AUI', 'ATUI', 'SATUI', 'SAB', 'DEF', 'SUPPRESS', 'CVF', 'ATN'],
    'MRDOC.RRF': ['DOCKEY', 'VALUE', 'TYPE', 'EXPL', 'MIN_LEN', 'MAX_LEN'],
    'MRFILES.RRF': ['FIL', 'DES', 'FMT', 'CLS', 'RWS', 'BTS', 'CRS', 'VER'],
    'MRHIER.RRF': ['CUI', 'AUI', 'CUI_PR', 'AUI_PR', 'SAB'],
    'MRMAP.RRF': ['MAPSETCUI', 'MAPSETSAB', 'MAPSUBSETID', 'MAPRANK', 'MAPVSAB', 'MAPATN', 'MAPATV', 'MAPIN_ID', 'MAPIN_TYPE', 'MAPOUT_ID', 'MAPOUT_TYPE', 'MAPRULE'],
    'MRRANK.RRF': ['RANK', 'MRRANK_COL', 'MRRANK_FIELD', 'RANK_TYPE', 'SUPPRESS'],
    'MRREL.RRF': ['CUI1', 'AUI1', 'STYPE1', 'REL', 'CUI2', 'AUI2', 'STYPE2', 'RELA', 'RUI', 'SRUI', 'SAB', 'SL', 'RG', 'DIR', 'SUPPRESS', 'CVF'],
    'MRSAB.RRF': ['VCUI', 'RCUI', 'VSAB', 'RSAB', 'SON', 'SF', 'SVER', 'VAB', 'RAB', 'LAT', 'CENC', 'TFR', 'CFR', 'CXTY', 'TTYL', 'ATBL', 'COL', 'FLN', 'VSAT', 'MAPSETKEY', 'MAPSETSIDE', 'FROMVSAB', 'TOVSAB', 'PREFGROUP'],
    'MRSAT.RRF': ['CUI', 'LUI', 'SUI', 'AUI', 'SCUI', 'SAB', 'ATN', 'ATV', 'SATUI', 'VSAB', 'SUPPRESS', 'CVF', 'ATUI', 'SG_TYPE'],
    'MRSMAP.RRF': ['MAPSETCUI', 'MAPSETSAB', 'MAPSUBSETID', 'MAPRANK', 'MAPVSAB', 'MAPATN', 'MAPATV', 'MAPIN_ID', 'MAPIN_TYPE', 'MAPOUT_ID', 'MAPOUT_TYPE', 'MAPRULE'],
    'MRSTY.RRF': ['CUI', 'TUI', 'STN', 'STY', 'ATUI', 'CVF'],
    'MRXW_ARA.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_BAQ.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_CHI.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_CZE.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_DAN.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_DUT.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_ENG.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_EST.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_FIN.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_FRE.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_GER.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_GRE.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_HEB.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_HUN.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_ISL.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_ITA.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_JPN.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_KOR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_LAV.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_LIT.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_NOR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_POL.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_POR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_RUS.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_SCR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_SPA.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_SWE.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_TUR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXW_UKR.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXNW_ENG.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB'],
    'MRXNS_ENG.RRF': ['CUI', 'AUI', 'STR', 'LANG', 'SAB']
}

In [10]:
import pandas as pd
from IPython.display import display

def read_rrf_and_display(file_path, file_description, column_names, nrows=10):
    """
    Reads an RRF file into a pandas DataFrame, displays the first N rows
    and column names, handling large files by reading only a specified number of rows.
    """
    print(f"Reading {file_description} from: {file_path}")
    try:
        df = pd.read_csv(
            file_path,
            sep='|',
            header=None,
            names=column_names, # Use the provided column names
            nrows=nrows,
            encoding='utf-8',
            on_bad_lines='skip'
        )

        print(f"Successfully read {file_description}.\n")
        print(f"First {nrows} rows of {file_description}:")
        display(df.head(nrows))

        print(f"\nColumn names (indices) of {file_description}:")
        print(df.columns.tolist())
        return df

    except FileNotFoundError:
        print(f"Error: The file '{file_path}' for {file_description} was not found.")
        return None
    except Exception as e:
        print(f"An error occurred while reading {file_description} from '{file_path}': {e}")
        return None

## Displaying sample data for individual RRF files

## MRFILES.RRF (Overall file descriptions)

MRFILES.RRF: This file describes all RRF files in the UMLS distribution.  
- **FIL**: File Name
- **DES**: Description
- **FMT**: Format
- **CLS**: Class
- **RWS**: Rows
- **BTS**: Bytes
- **CRS**: Checksum
- **VER**: Version

In [43]:
file_path_mrfiles = '/content/drive/MyDrive/UMLS/2025RRFs/MRFILES.RRF'
df_mrfiles = read_rrf_and_display(file_path_mrfiles, 'MRFILES.RRF', rrf_column_definitions['MRFILES.RRF'], nrows=10)

Reading MRFILES.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRFILES.RRF
Successfully read MRFILES.RRF.

First 10 rows of MRFILES.RRF:

,FIL,DES,FMT,CLS,RWS,BTS,CRS,VER
0,AMBIGLUI.RRF,Ambiguous term identifiers,"LUI,CUI",2,441598,8511777,NaN,NaN
1,AMBIGSUI.RRF,Ambiguous string identifiers,"SUI,CUI",2,330922,6409955,NaN,NaN
2,CHANGE/DELETEDCUI.RRF,Deleted concepts,"PCUI,PSTR",2,3694,278497,NaN,NaN
3,CHANGE/DELETEDLUI.RRF,Deleted terms,"PLUI,PSTR",2,55891,3763345,NaN,NaN
4,CHANGE/DELETEDSUI.RRF,Deleted strings,"PSUI,LAT,PSTR",3,65790,4821091,NaN,NaN
5,CHANGE/MERGEDCUI.RRF,Merged concepts,"PCUI,CUI",2,3831,72789,NaN,NaN
6,CHANGE/MERGEDLUI.RRF,Merged terms,"PLUI,LUI",2,0,0,NaN,NaN
7,MRAUI.RRF,AUI History,"AUI1,CUI1,VER,REL,RELA,MAPREASON,AUI2,CUI2,MAPIN",9,351617,19061141,NaN,NaN
8,MRCOLS.RRF,Attribute Relation,"COL,DES,REF,MIN,AV,MAX,FIL,DTY",8,349,24053,NaN,NaN
9,MRCONSO.RRF,Concept names and sources,"CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SD...",18,17390109,2249744397,NaN,NaN

Column names (indices) of MRFILES.RRF:
['FIL', 'DES', 'FMT', 'CLS', 'RWS', 'BTS', 'CRS', 'VER']

## MRCOLS.RRF (Column definitions for all RRF files)

MRCOLS.RRF: This file describes the columns of the UMLS RRF files.  
- **COL**: Column Name
- **COL_NM**: Column Name (Full)
- **FLG**: Flag
- **FBG**: Field Byte Group
- **FBL**: Field Byte Length
- **DIR_NM**: Directory Name
- **FIL**: File
- **MIN_LEN**: Minimum Length
- **MAX_LEN**: Maximum Length
- **DATA_TY**: Data Type

In [28]:
file_path_mrcols = '/content/drive/MyDrive/UMLS/2025RRFs/MRCOLS.RRF'
df_mrcols = read_rrf_and_display(file_path_mrcols, 'MRCOLS.RRF', rrf_column_definitions['MRCOLS.RRF'], nrows=10)

Reading MRCOLS.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRCOLS.RRF
Successfully read MRCOLS.RRF.

First 10 rows of MRCOLS.RRF:

,COL,COL_NM,FLG,FBG,FBL,DIR_NM,FIL,MIN_LEN,MAX_LEN,DATA_TY
0,ATNL,Attribute name list for a source.,NaN,0,72.06,1178,MRSAB.RRF,varchar(4000),NaN,NaN
1,ATN,Attribute name,NaN,2,11.49,62,MRSAT.RRF,varchar(100),NaN,NaN
2,ATUI,Unique identifier for attribute.,NaN,10,10.65,11,MRSTY.RRF,varchar(11),NaN,NaN
3,ATUI,Unique identifier for attribute.,NaN,10,10.88,11,MRDEF.RRF,varchar(11),NaN,NaN
4,ATUI,Unique identifier for attribute.,NaN,10,10.89,11,MRSAT.RRF,varchar(11),NaN,NaN
5,ATV,Attribute value,NaN,1,14.12,35985,MRSAT.RRF,varchar(65000),NaN,NaN
6,AUI1,Unique identifier for first atom,NaN,0,8.56,9,MRREL.RRF,varchar(9),NaN,NaN
7,AUI1,Unique identifier for first atom,NaN,8,8.60,9,MRAUI.RRF,varchar(9),NaN,NaN
8,AUI2,Unique identifier for second atom,NaN,0,8.56,9,MRREL.RRF,varchar(9),NaN,NaN
9,AUI2,Unique identifier for second atom,NaN,8,8.60,9,MRAUI.RRF,varchar(9),NaN,NaN

Column names (indices) of MRCOLS.RRF:
['COL', 'COL_NM', 'FLG', 'FBG', 'FBL', 'DIR_NM', 'FIL', 'MIN_LEN', 'MAX_LEN', 'DATA_TY']

## MRDOC.RRF (General UMLS documentation)

MRDOC.RRF: This file contains documentation about the UMLS Metathesaurus data.  
- **DOCKEY**: Documentation Key
- **VALUE**: Value
- **TYPE**: Type
- **EXPL**: Explanation
- **MIN_LEN**: Minimum Length
- **MAX_LEN**: Maximum Length

In [49]:
file_path_mrdoc = '/content/drive/MyDrive/UMLS/2025RRFs/MRDOC.RRF'
df_mrdoc = read_rrf_and_display(file_path_mrdoc, 'MRDOC.RRF', rrf_column_definitions['MRDOC.RRF'], nrows=10)

Reading MRDOC.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRDOC.RRF
Successfully read MRDOC.RRF.

First 10 rows of MRDOC.RRF:

,DOCKEY,VALUE,TYPE,EXPL,MIN_LEN,MAX_LEN
0,ATN,AAL_TERM,expanded_form,AAL term,NaN,NaN
1,ATN,ACCEPTABILITYID,expanded_form,Acceptability Id,NaN,NaN
2,ATN,ACCEPTED_THERAPEUTIC_USE_FOR,expanded_form,Accepted therapeutic use for,NaN,NaN
3,ATN,ACTIVE,expanded_form,Active,NaN,NaN
4,ATN,ADDED_MEANING,expanded_form,Additional descriptive information,NaN,NaN
5,ATN,ADDITIONAL_GUIDELINE,expanded_form,Additional explanatory text that is applicable...,NaN,NaN
6,ATN,ADDON_CODE,expanded_form,"A ""T"" in this field indicates that it is an ""A...",NaN,NaN
7,ATN,AGR,expanded_form,Alliance of Genome Resources,NaN,NaN
8,ATN,AMBIGUITY_FLAG,expanded_form,Source atom ambiguity flag,NaN,NaN
9,ATN,AMT,expanded_form,AOT uses MeSH term,NaN,NaN

Column names (indices) of MRDOC.RRF:
['DOCKEY', 'VALUE', 'TYPE', 'EXPL', 'MIN_LEN', 'MAX_LEN']

## MRSAB.RRF (Source vocabularies information)

MRSAB.RRF: This file contains information about source vocabularies.  
- **VCUI**: Versioned Concept Unique Identifier
- **RCUI**: Root Concept Unique Identifier
- **VSAB**: Versioned Source Abbreviation
- **RSAB**: Root Source Abbreviation
- **SON**: Source Official Name
- **SF**: Source Family
- **SVER**: Source Version
- **VAB**: Versioned Abbreviation
- **RAB**: Root Abbreviation
- **LAT**: Language
- **CENC**: Content Encoding
- **TFR**: Term Frequencies
- **CFR**: Concept Frequencies
- **CXTY**: Context Type
- **TTYL**: Term Type List
- **ATBL**: Attribute Table
- **COL**: Column
- **FLN**: Full Name
- **VSAT**: Versioned Source Attribute Table
- **MAPSETKEY**: Map Set Key
- **MAPSETSIDE**: Map Set Side
- **FROMVSAB**: From Versioned Source Abbreviation
- **TOVSAB**: To Versioned Source Abbreviation
- **PREFGROUP**: Preferred Group

In [17]:
file_path_mrsab = '/content/drive/MyDrive/UMLS/2025RRFs/MRSAB.RRF'
df_mrsab = read_rrf_and_display(file_path_mrsab, 'MRSAB.RRF', rrf_column_definitions['MRSAB.RRF'], nrows=10)

Reading MRSAB.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRSAB.RRF
Successfully read MRSAB.RRF.

First 10 rows of MRSAB.RRF:

,,VCUI,RCUI,VSAB,RSAB,SON,SF,SVER,VAB,RAB,LAT,...,TTYL,ATBL,COL,FLN,VSAT,MAPSETKEY,MAPSETSIDE,FROMVSAB,TOVSAB,PREFGROUP
C1140092,C1140091,AIR93,AIR,"AI/RHEUM, 1993",AIR,1993,NaN,NaN,1995AA,NaN,May Cheh;;Lister Hill National Center for Biom...,...,FULL-MULTIPLE,"DI,FI,HT,SY",NaN,ENG,UTF-8,Y,Y,AI/RHEUM,";;;;AI/RHEUM;;;;;National Library of Medicine,...",NaN
C1140098,C1140097,CST95,CST,"COSTART, 1995",CST,1995,NaN,NaN,1999AA,NaN,;;National Technical Information Service ;;;;;...,...,FULL-MULTIPLE,"GT,HT,PT,SC",NaN,ENG,UTF-8,Y,Y,COSTART,;;;;Coding Symbols for Thesaurus of Adverse Re...,NaN
C1140099,C1140100,DXP94,DXP,"DXplain, 1994",DXP,1994,NaN,NaN,1995AA,NaN,"G. Octo Barnett, M.D.;;Laboratory of Computer ...",...,NaN,"DI,FI,SY",NaN,ENG,UTF-8,Y,Y,DXplain,;;;;DXplain (An expert diagnosis program);;;;B...,NaN
C1140105,C1140106,LCH90,LCH,"Library of Congress Subject Headings, 1990",LCH,1990,NaN,NaN,1992AA,NaN,;;;;;;;;;;;;http://www.lcweb.loc.gov,...,NaN,PT,NaN,ENG,UTF-8,Y,Y,Library of Congress Subject Headings,;;;;Library of Congress Subject Headings;;;12t...,NaN
C1140107,C1140108,MCM92,MCM,"McMaster University Epidemiology Terms, 1992",MCM,1992,NaN,NaN,1992AA,NaN,"R. Brian Haynes, M.D., Ph.D.;; Clinical Epidem...",...,NaN,"PT,RT",NaN,ENG,UTF-8,Y,Y,Glossary of Clinical Epidemiologic Terms,;;;;Glossary of Methodologic Terms for Clinica...,NaN
C1140117,C1140116,SNM2,SNM,"SNOMED-2, 2",SNM,2,NaN,NaN,1991AA,NaN,Jill Rosenthal/Naomi Siebert;;College of Ameri...,...,FULL-MULTIPLE,"HT,PT,RS,RT,SY",NaN,ENG,UTF-8,Y,Y,SNOMED 1982,";;;Cote, Roger A.;Systematized Nomenclature of...",NaN
C1140119,C1140118,SNMI98,SNMI,"SNOMED International, 1998",SNMI,1998,NaN,NaN,1999AA,NaN,Jill Rosenthal/Naomi Siebert;;College of Ameri...,...,FULL,"AD,HT,HX,PT,PX,RT,SX,SY","EZ,SB,SHF,SIC,SMX",ENG,UTF-8,Y,Y,SNOMED Intl 1998,"Cote, Roger A.;;College of American Pathologis...",NaN
C1140122,C1140123,WHO97,WHO,"WHO Adverse Reaction Terminology, 1997",WHO,1997,NaN,NaN,1999AA,NaN,;;WHO Collaborating Centre for International D...,...,FULL-MULTIPLE,"HT,IT,OS,PT",NaN,ENG,UTF-8,Y,Y,WHOART,;;;;WHO Adverse Drug Reaction Terminology (WHO...,NaN
C1140127,C1140126,ULT93,ULT,"UltraSTAR, 1993",ULT,1993,NaN,NaN,1995AA,NaN,"Robert Greenes, M.D., Ph.D.;;Brigham & Womens ...",...,NaN,PT,NaN,ENG,UTF-8,Y,Y,UltraSTAR,"Bell, Douglas;;;;Ultrasound Structured Attribu...",NaN
C1140144,C1137110,ICD10_1998,ICD10,"ICD10, 1998",ICD10,1998,NaN,NaN,2004AB,NaN,";;Office of Publications, World Health Organiz...",...,FULL,"HS,HT,HX,PS,PT,PX",NaN,ENG,UTF-8,Y,Y,International Classification of Diseases and R...,;;;;International Statistical Classification o...,NaN

Column names (indices) of MRSAB.RRF:
['VCUI', 'RCUI', 'VSAB', 'RSAB', 'SON', 'SF', 'SVER', 'VAB', 'RAB', 'LAT', 'CENC', 'TFR', 'CFR', 'CXTY', 'TTYL', 'ATBL', 'COL', 'FLN', 'VSAT', 'MAPSETKEY', 'MAPSETSIDE', 'FROMVSAB', 'TOVSAB', 'PREFGROUP']

## MRRANK.RRF (Ranking information for UMLS elements)

MRRANK.RRF: This file provides ranking information for different UMLS data elements.  
- **RANK**: Rank
- **MRRANK_COL**: MRRANK Column
- **MRRANK_FIELD**: MRRANK Field
- **RANK_TYPE**: Rank Type
- **SUPPRESS**: Suppressibility

In [53]:
file_path_mrrank = '/content/drive/MyDrive/UMLS/2025RRFs/MRRANK.RRF'
df_mrrank = read_rrf_and_display(file_path_mrrank, 'MRRANK.RRF', rrf_column_definitions['MRRANK.RRF'], nrows=10)

Reading MRRANK.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRRANK.RRF
Successfully read MRRANK.RRF.

First 10 rows of MRRANK.RRF:

   RANK MRRANK_COL MRRANK_FIELD RANK_TYPE  SUPPRESS
0   916        MTH           PN         N       NaN
1   915  MTHCMSFRF           PT         N       NaN
2   914     RXNORM          SCD         N       NaN
3   913     RXNORM          SBD         N       NaN
4   912     RXNORM         SCDG         N       NaN
5   911     RXNORM        SCDGP         N       NaN
6   910     RXNORM         SBDG         N       NaN
7   909     RXNORM         BPCK         N       NaN
8   908     RXNORM         GPCK         N       NaN
9   907     RXNORM           IN         N       NaN

Column names (indices) of MRRANK.RRF:
['RANK', 'MRRANK_COL', 'MRRANK_FIELD', 'RANK_TYPE', 'SUPPRESS']

## MRCONSO.RRF (Core concept names and terms)

MRCONSO.RRF: This is the main file containing all concept names and terms.  
- **CUI**: Concept Unique Identifier
- **LAT**: Language
- **TS**: Term Status
- **LUI**: Lexical Unique Identifier
- **STT**: String Type
- **SUI**: String Unique Identifier
- **ISPREF**: Is Preferred
- **AUI**: Atom Unique Identifier
- **SAUI**: Source Atom Unique Identifier
- **SCUI**: Source Concept Unique Identifier
- **SDUI**: Source Descriptor Unique Identifier
- **SAB**: Source Abbreviation
- **TTY**: Term Type
- **CODE**: Source Vocab Code
- **STR**: String
- **SRL**: Source Row ID
- **SUPPRESS**: Suppressibility
- **CVF**: Content View Flag

In [13]:
file_path_mrconso = '/content/drive/MyDrive/UMLS/2025RRFs/MRCONSO.RRF'
df_mrconso = read_rrf_and_display(file_path_mrconso, 'MRCONSO.RRF', rrf_column_definitions['MRCONSO.RRF'], nrows=10)

Reading MRCONSO.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRCONSO.RRF
Successfully read MRCONSO.RRF.

First 10 rows of MRCONSO.RRF:

,CUI,LAT,TS,LUI,STT,SUI,ISPREF,AUI,SAUI,SCUI,SDUI,SAB,TTY,CODE,STR,SRL,SUPPRESS,CVF
C0000005,ENG,P,L0000005,PF,S0007492,Y,A26634265,NaN,M0019694,D012711,MSH,PEP,D012711,(131)I-Macroaggregated Albumin,0,N,NaN,NaN
C0000005,ENG,S,L0270109,PF,S0007491,Y,A26634266,NaN,M0019694,D012711,MSH,ET,D012711,(131)I-MAA,0,N,NaN,NaN
C0000005,FRE,P,L6220710,PF,S7133957,Y,A13433185,NaN,M0019694,D012711,MSHFRE,PEP,D012711,Macroagrégats d'albumine marquée à l'iode 131,3,N,NaN,NaN
C0000005,FRE,S,L6215648,PF,S7133916,Y,A27488794,NaN,M0019694,D012711,MSHFRE,ET,D012711,MAA-I 131,3,N,NaN,NaN
C0000005,FRE,S,L6215656,PF,S7133956,Y,A27614225,NaN,M0019694,D012711,MSHFRE,ET,D012711,Macroagrégats d'albumine humaine marquée à l'i...,3,N,NaN,NaN
C0000005,SWE,P,L17197376,PF,S20758072,Y,A33245954,NaN,M0019694,D012711,MSHSWE,ET,D012711,(131)I-Makroaggregerat albumin,3,N,NaN,NaN
C0000039,CZE,P,L6742182,PF,S7862052,Y,A13042554,NaN,M0023172,D015060,MSHCZE,MH,D015060,"1,2-dipalmitoylfosfatidylcholin",3,N,NaN,NaN
C0000039,CZE,S,L16793135,PF,S20338296,Y,A32647442,NaN,M0023172,D015060,MSHCZE,ET,D015060,DPPC,3,N,NaN,NaN
C0000039,CZE,S,L16793722,PF,S20342801,Y,A32637908,NaN,M0023172,D015060,MSHCZE,ET,D015060,dipalmitoylfosfatidylcholin,3,N,NaN,NaN
C0000039,CZE,S,L16794994,PF,S20342800,Y,A32637907,NaN,M0023172,D015060,MSHCZE,ET,D015060,dipalmitoyl-fosfatidylcholin,3,N,NaN,NaN

Column names (indices) of MRCONSO.RRF:
['CUI', 'LAT', 'TS', 'LUI', 'STT', 'SUI', 'ISPREF', 'AUI', 'SAUI', 'SCUI', 'SDUI', 'SAB', 'TTY', 'CODE', 'STR', 'SRL', 'SUPPRESS', 'CVF']

## AMBIGLUI.RRF (Ambiguous lexical identifiers)

AMBIGLUI.RRF: This file contains ambiguous term identifiers.  
- **LUI**: Lexical Unique Identifier
- **CUI**: Concept Unique Identifier
- **VER**: Version

In [12]:
file_path_ambiglui = '/content/drive/MyDrive/UMLS/2025RRFs/AMBIGLUI.RRF'
df_ambiglui = read_rrf_and_display(file_path_ambiglui, 'AMBIGLUI.RRF', rrf_column_definitions['AMBIGLUI.RRF'], nrows=10)

Reading AMBIGLUI.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/AMBIGLUI.RRF
Successfully read AMBIGLUI.RRF.

First 10 rows of AMBIGLUI.RRF:

        LUI       CUI  VER
0  L0000003  C0010504  NaN
1  L0000003  C0917995  NaN
2  L0000032  C0010206  NaN
3  L0000032  C0010207  NaN
4  L0000052  C0000052  NaN
5  L0000052  C1415001  NaN
6  L0000114  C0010139  NaN
7  L0000114  C0201970  NaN
8  L0000123  C0003691  NaN
9  L0000123  C1412356  NaN

Column names (indices) of AMBIGLUI.RRF:
['LUI', 'CUI', 'VER']

## AMBIGSUI.RRF (Ambiguous string identifiers)

AMBIGSUI.RRF: This file contains ambiguous string identifiers.  
- **SUI**: String Unique Identifier
- **CUI**: Concept Unique Identifier
- **VER**: Version

In [32]:
file_path_ambigsui = '/content/drive/MyDrive/UMLS/2025RRFs/AMBIGSUI.RRF'
df_ambigsui = read_rrf_and_display(file_path_ambigsui, 'AMBIGSUI.RRF', rrf_column_definitions['AMBIGSUI.RRF'], nrows=10)

Reading AMBIGSUI.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/AMBIGSUI.RRF
Successfully read AMBIGSUI.RRF.

First 10 rows of AMBIGSUI.RRF:

        SUI       CUI  VER
0  S0000005  C0025362  NaN
1  S0000005  C3161331  NaN
2  S0000022  C0003477  NaN
3  S0000022  C1527281  NaN
4  S0000024  C0029942  NaN
5  S0000024  C0270307  NaN
6  S0000038  C0020795  NaN
7  S0000038  C0236819  NaN
8  S0000055  C0006647  NaN
9  S0000055  C0274693  NaN

Column names (indices) of AMBIGSUI.RRF:
['SUI', 'CUI', 'VER']

## MRAUI.RRF (Atom unique identifiers)

MRAUI.RRF: This file contains information about atoms.  
- **AUI**: Atom Unique Identifier
- **CUI**: Concept Unique Identifier
- **LUI**: Lexical Unique Identifier
- **SUI**: String Unique Identifier
- **SAP**: Source Atom Position
- **VER**: Version

In [33]:
file_path_mraui = '/content/drive/MyDrive/UMLS/2025RRFs/MRAUI.RRF'
df_mraui = read_rrf_and_display(file_path_mraui, 'MRAUI.RRF', rrf_column_definitions['MRAUI.RRF'], nrows=10)

Reading MRAUI.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRAUI.RRF
Successfully read MRAUI.RRF.

First 10 rows of MRAUI.RRF:

                              AUI   CUI       LUI       SUI SAP  VER
A0000039 C1411876 2022AA NaN  NaN  move  A0000039  C0869474   Y  NaN
A0000049 C0003910 2005AB NaN  NaN  move  A0000049  C0236828   Y  NaN
A0000080 C0003477 2011AA NaN  NaN  move  A0000080  C1527281   Y  NaN
A0000087 C0596170 2008AB NaN  NaN  move  A0000087  C2267227   Y  NaN
A0000088 C0596170 2008AB NaN  NaN  move  A0000088  C2267227   Y  NaN
A0000090 C0596170 2008AB NaN  NaN  move  A0000090  C2267227   Y  NaN
A0000091 C0596170 2008AB NaN  NaN  move  A0000091  C2267227   Y  NaN
A0000092 C0596170 2008AB NaN  NaN  move  A0000092  C2267227   Y  NaN
A0000174 C0006872 2025AA NaN  NaN  move  A0000174  C5945053   Y  NaN
A0000230 C0029220 2007AA NaN  NaN  move  A0000230  C0236748   Y  NaN

Column names (indices) of MRAUI.RRF:
['AUI', 'CUI', 'LUI', 'SUI', 'SAP', 'VER']

## MRDEF.RRF (Concept definitions)

MRDEF.RRF: This file contains definitions for concepts.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **ATUI**: Attribute Unique Identifier
- **SATUI**: Source Attribute Unique Identifier
- **SAB**: Source Abbreviation
- **DEF**: Definition
- **SUPPRESS**: Suppressibility
- **CVF**: Content View Flag
- **ATN**: Attribute Name

In [14]:
file_path_mrdef = '/content/drive/MyDrive/UMLS/2025RRFs/MRDEF.RRF'
df_mrdef = read_rrf_and_display(file_path_mrdef, 'MRDEF.RRF', rrf_column_definitions['MRDEF.RRF'], nrows=10)

Reading MRDEF.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRDEF.RRF
Successfully read MRDEF.RRF.

First 10 rows of MRDEF.RRF:

,CUI,AUI,ATUI,SATUI,SAB,DEF,SUPPRESS,CVF,ATN
0,C0000039,A0016515,AT38152019,NaN,MSH,Synthetic phospholipid used in liposomes and l...,N,NaN,NaN
1,C0000039,A11754881,AT69817678,NaN,MSHSWE,Syntetisk fosfolipid som används i liposomer o...,N,NaN,NaN
2,C0000039,A13042554,AT264439104,NaN,MSHCZE,Syntetický fosfolipid používaný v liposomech a...,N,NaN,NaN
3,C0000039,A13096036,AT254753550,NaN,MSHPOR,Fosfolipídeo sintético utilizado em lipossomos...,N,NaN,NaN
4,C0000039,A9176213,AT267611046,NaN,MSHSPA,Fosfolípido sintético que se utiliza en liposo...,N,NaN,NaN
5,C0000052,A0016535,AT38148809,NaN,MSH,"In glycogen or amylopectin synthesis, the enzy...",N,NaN,NaN
6,C0000052,A11754882,AT69816285,NaN,MSHSWE,I glykogen- eller amylopektinsyntes är detta e...,N,NaN,NaN
7,C0000052,A13046704,AT264439851,NaN,MSHCZE,"Enzym, který při syntéze glykogenu nebo amylop...",N,NaN,NaN
8,C0000052,A9139513,AT254753551,NaN,MSHPOR,"Na síntese de glicogênio ou amilopectina, a en...",N,NaN,NaN
9,C0000052,A9230837,AT267611047,NaN,MSHSPA,"Es la enzima que, en la síntesis de glucógeno ...",N,NaN,NaN

Column names (indices) of MRDEF.RRF:
['CUI', 'AUI', 'ATUI', 'SATUI', 'SAB', 'DEF', 'SUPPRESS', 'CVF', 'ATN']

## MRSTY.RRF (Semantic types for concepts)

MRSTY.RRF: This file links CUIs to Semantic Types (STYs).  
- **CUI**: Concept Unique Identifier
- **TUI**: Tree Unique Identifier
- **STN**: Semantic Type Node
- **STY**: Semantic Type
- **ATUI**: Attribute Unique Identifier
- **CVF**: Content View Flag

In [16]:
file_path_mrsty = '/content/drive/MyDrive/UMLS/2025RRFs/MRSTY.RRF'
df_mrsty = read_rrf_and_display(file_path_mrsty, 'MRSTY.RRF', rrf_column_definitions['MRSTY.RRF'], nrows=10)

Reading MRSTY.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRSTY.RRF
Successfully read MRSTY.RRF.

First 10 rows of MRSTY.RRF:

           CUI  TUI  STN  STY  ATUI  CVF
C0000005  T116  NaN  NaN  NaN   NaN  NaN
C0000005  T121  NaN  NaN  NaN   NaN  NaN
C0000005  T130  NaN  NaN  NaN   NaN  NaN
C0000039  T109  NaN  NaN  NaN   NaN  NaN
C0000039  T121  NaN  NaN  NaN   NaN  NaN
C0000052  T116  NaN  NaN  NaN   NaN  NaN
C0000052  T126  NaN  NaN  NaN   NaN  NaN
C0000074  T109  NaN  NaN  NaN   NaN  NaN
C0000084  T116  NaN  NaN  NaN   NaN  NaN
C0000084  T123  NaN  NaN  NaN   NaN  NaN

Column names (indices) of MRSTY.RRF:
['CUI', 'TUI', 'STN', 'STY', 'ATUI', 'CVF']

## MRREL.RRF (Relationships between concepts and atoms)

MRREL.RRF: This file contains relationships between concepts and atoms.  
- **CUI1**: Concept Unique Identifier 1
- **AUI1**: Atom Unique Identifier 1
- **STYPE1**: Source Type 1
- **REL**: Relationship Type
- **CUI2**: Concept Unique Identifier 2
- **AUI2**: Atom Unique Identifier 2
- **STYPE2**: Source Type 2
- **RELA**: Relationship Attribute
- **RUI**: Relationship Unique Identifier
- **SRUI**: Source Relationship Unique Identifier
- **SAB**: Source Abbreviation
- **SL**: Source Level
- **RG**: Relationship Group
- **DIR**: Direction
- **SUPPRESS**: Suppressibility
- **CVF**: Content View Flag

In [15]:
file_path_mrrel = '/content/drive/MyDrive/UMLS/2025RRFs/MRREL.RRF'
df_mrrel = read_rrf_and_display(file_path_mrrel, 'MRREL.RRF', rrf_column_definitions['MRREL.RRF'], nrows=10)

Reading MRREL.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRREL.RRF
Successfully read MRREL.RRF.

First 10 rows of MRREL.RRF:

,CUI1,AUI1,STYPE1,REL,CUI2,AUI2,STYPE2,RELA,RUI,SRUI,SAB,SL,RG,DIR,SUPPRESS,CVF
C0000005,A13433185,SCUI,RB,C0036775,A7466261,SCUI,NaN,R86000559,NaN,MSHFRE,NaN,NaN,NaN,N,NaN,NaN
C0000005,A26634265,SCUI,RB,C0036775,A0115649,SCUI,NaN,R31979041,NaN,MSH,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A11754881,AUI,translation_of,R101808683,NaN,MSHSWE,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A12091182,AUI,entry_version_of,R64592881,NaN,MSH,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A13042554,AUI,translation_of,R193408122,NaN,MSHCZE,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A13096036,AUI,translation_of,R73331672,NaN,MSHPOR,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A1317708,AUI,permuted_term_of,R28482432,NaN,MSH,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A18972171,AUI,translation_of,R124061564,NaN,MSHPOL,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A7439429,AUI,translation_of,R193377655,NaN,MSHFRE,NaN,NaN,NaN,N,NaN,NaN
C0000039,A0016515,AUI,SY,C0000039,A7480660,AUI,translation_of,R206578450,NaN,MSHGER,NaN,NaN,NaN,N,NaN,NaN

Column names (indices) of MRREL.RRF:
['CUI1', 'AUI1', 'STYPE1', 'REL', 'CUI2', 'AUI2', 'STYPE2', 'RELA', 'RUI', 'SRUI', 'SAB', 'SL', 'RG', 'DIR', 'SUPPRESS', 'CVF']

## MRHIER.RRF (Hierarchical relationships)

MRHIER.RRF: This file defines hierarchical relationships between concepts.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **CUI_PR**: Parent Concept Unique Identifier
- **AUI_PR**: Parent Atom Unique Identifier
- **SAB**: Source Abbreviation

In [18]:
file_path_mrhier = '/content/drive/MyDrive/UMLS/2025RRFs/MRHIER.RRF'
df_mrhier = read_rrf_and_display(file_path_mrhier, 'MRHIER.RRF', rrf_column_definitions['MRHIER.RRF'], nrows=10)

Reading MRHIER.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRHIER.RRF
Successfully read MRHIER.RRF.

First 10 rows of MRHIER.RRF:

                                 CUI  \
C0000039 A0016515  1 NaN MSH     NaN
         A0049238  1 NaN SNMI    NaN
         A11754881 1 NaN MSHSWE  NaN
         A13042554 1 NaN MSHCZE  NaN
         A13096036 1 NaN MSHPOR  NaN
         A13424401 1 NaN MSHFIN  NaN
         A15722927 1 NaN MSHJPN  NaN
         A18972171 1 NaN MSHPOL  NaN
         A32917594 1 NaN LNC     NaN
NaN      NaN       2 NaN NaN     NaN

                                                                               AUI  \
C0000039 A0016515  1 NaN MSH     A0434168.A2367943.A18456972.A0135374.A0080362....
         A0049238  1 NaN SNMI                  A0455478.A0359059.A0650841.A0699760
         A11754881 1 NaN MSHSWE  A16484106.A11749657.A11756438.A11755673.A11764...
         A13042554 1 NaN MSHCZE  A13057283.A13041599.A13058474.A13041962.A13058...
         A13096036 1 NaN MSHPOR  A13098313.A9119566.A20010020.A9113667.A9114687...
         A13424401 1 NaN MSHFIN  A13407135.A13414261.A13414316.A13414530.A13416...
         A15722927 1 NaN MSHJPN  A15700182.A15694289.A15685703.A15721537.A15684...
         A18972171 1 NaN MSHPOL  A18992175.A18972698.A18983027.A18998463.A18982...
         A32917594 1 NaN LNC     A6321000.A32818398.A34755242.A32898011.A327574...
NaN      NaN       2 NaN NaN     ..A34755242.A32898011.A32821540.A32866223.A327...

                                                          CUI_PR  AUI_PR  SAB
C0000039 A0016515  1 NaN MSH     D10.570.755.375.760.400.800.224     NaN  NaN
         A0049238  1 NaN SNMI                                NaN     NaN  NaN
         A11754881 1 NaN MSHSWE  D10.570.755.375.760.400.800.224     NaN  NaN
         A13042554 1 NaN MSHCZE  D10.570.755.375.760.400.800.224     NaN  NaN
         A13096036 1 NaN MSHPOR  D10.570.755.375.760.400.800.224     NaN  NaN
         A13424401 1 NaN MSHFIN  D10.570.755.375.760.400.800.224     NaN  NaN
         A15722927 1 NaN MSHJPN  D10.570.755.375.760.400.800.224     NaN  NaN
         A18972171 1 NaN MSHPOL  D10.570.755.375.760.400.800.224     NaN  NaN
         A32917594 1 NaN LNC                                 NaN     NaN  NaN
NaN      NaN       2 NaN NaN                                 NaN     NaN  NaN

Column names (indices) of MRHIER.RRF:
['CUI', 'AUI', 'CUI_PR', 'AUI_PR', 'SAB']

## MRSAT.RRF (Additional attributes)

MRSAT.RRF: This file contains additional information (attributes) about atoms, concepts, and other entities.  
- **CUI**: Concept Unique Identifier
- **LUI**: Lexical Unique Identifier
- **SUI**: String Unique Identifier
- **AUI**: Atom Unique Identifier
- **SCUI**: Source Concept Unique Identifier
- **SAB**: Source Abbreviation
- **ATN**: Attribute Name
- **ATV**: Attribute Value
- **SATUI**: Source Attribute Unique Identifier
- **VSAB**: Versioned Source Abbreviation
- **SUPPRESS**: Suppressibility
- **CVF**: Content View Flag
- **ATUI**: Attribute Unique Identifier
- **SG_TYPE**: Semantic Group Type

In [34]:
file_path_mrsat = '/content/drive/MyDrive/UMLS/2025RRFs/MRSAT.RRF'
df_mrsat = read_rrf_and_display(file_path_mrsat, 'MRSAT.RRF', rrf_column_definitions['MRSAT.RRF'], nrows=10)

Reading MRSAT.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRSAT.RRF
Successfully read MRSAT.RRF.

First 10 rows of MRSAT.RRF:

,CUI,LUI,SUI,AUI,SCUI,SAB,ATN,ATV,SATUI,VSAB,SUPPRESS,CVF,ATUI,SG_TYPE
0,C0000005,NaN,NaN,A26634265,AUI,NaN,AT212456753,NaN,TH,MSH,UNK (19XX),N,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,AT212480766,NaN,TERMUI,NaN,T037573,N,NaN,NaN
2,C0000005,NaN,NaN,A26634265,SCUI,NaN,AT60774257,NaN,RN,MSH,0,N,NaN,NaN
3,C0000005,NaN,NaN,A26634266,AUI,NaN,AT212327137,NaN,TERMUI,MSH,T037574,N,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,AT212456754,NaN,TH,NaN,UNK (19XX),N,NaN,NaN
5,C0000005,NaN,NaN,NaN,CUI,NaN,AT00368929,NaN,DA,MTH,19900930,N,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,AT02319637,NaN,ST,NaN,R,N,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,AT269759383,NaN,MR,NaN,20210805,N,NaN,NaN
8,C0000039,NaN,NaN,A26674543,AUI,NaN,AT212481191,NaN,TH,MSH,UNK (19XX),N,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,AT212562015,NaN,TERMUI,NaN,T043933,N,NaN,NaN

Column names (indices) of MRSAT.RRF:
['CUI', 'LUI', 'SUI', 'AUI', 'SCUI', 'SAB', 'ATN', 'ATV', 'SATUI', 'VSAB', 'SUPPRESS', 'CVF', 'ATUI', 'SG_TYPE']

## MRCUI.RRF (Concept unique identifiers information)

MRCUI.RRF: This file contains information about concepts (CUI).  
- **CUI1**: Concept Unique Identifier 1
- **CUI2**: Concept Unique Identifier 2
- **VCUI**: Versioned Concept Unique Identifier

In [50]:
file_path_mrcui = '/content/drive/MyDrive/UMLS/2025RRFs/MRCUI.RRF'
df_mrcui = read_rrf_and_display(file_path_mrcui, 'MRCUI.RRF', rrf_column_definitions['MRCUI.RRF'], nrows=10)

Reading MRCUI.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRCUI.RRF
Successfully read MRCUI.RRF.

First 10 rows of MRCUI.RRF:

                                 CUI1 CUI2  VCUI
C0000002 2000AC SY  NaN NaN  C0007404    Y   NaN
C0000003 1999AA SY  NaN NaN  C0010504    Y   NaN
C0000024 1993AA SY  NaN NaN  C0043791    Y   NaN
C0000105 1995AA SY  NaN NaN  C0001964    Y   NaN
C0000136 1993AA DEL NaN NaN       NaN  NaN   NaN
C0000140 1993AA DEL NaN NaN       NaN  NaN   NaN
C0000158 1993AA DEL NaN NaN       NaN  NaN   NaN
C0000164 2003AB RO  NaN NaN  C0000163    Y   NaN
C0000177 1993AA SY  NaN NaN  C0014924    Y   NaN
C0000219 1993AA DEL NaN NaN       NaN  NaN   NaN

Column names (indices) of MRCUI.RRF:
['CUI1', 'CUI2', 'VCUI']

## MRMAP.RRF (Mapping information between terminologies)

MRMAP.RRF: This file contains mapping information between different terminologies.  
- **MAPSETCUI**: Map Set Concept Unique Identifier
- **MAPSETSAB**: Map Set Source Abbreviation
- **MAPSUBSETID**: Map Subset ID
- **MAPRANK**: Map Rank
- **MAPVSAB**: Map Versioned Source Abbreviation
- **MAPATN**: Map Attribute Name
- **MAPATV**: Map Attribute Value
- **MAPIN_ID**: Map Input ID
- **MAPIN_TYPE**: Map Input Type
- **MAPOUT_ID**: Map Output ID
- **MAPOUT_TYPE**: Map Output Type
- **MAPRULE**: Mapping Rule

In [45]:
file_path_mrmap = '/content/drive/MyDrive/UMLS/2025RRFs/MRMAP.RRF'
df_mrmap = read_rrf_and_display(file_path_mrmap, 'MRMAP.RRF', rrf_column_definitions['MRMAP.RRF'], nrows=10)

Reading MRMAP.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRMAP.RRF
Successfully read MRMAP.RRF.

First 10 rows of MRMAP.RRF:

                                                                                    MAPSETCUI  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026        NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080        NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713        NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251        NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161        NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437        NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442        NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087        NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776        NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522        NaN

                                                                                                                            MAPSETSAB  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026  <Hypertension, Renovascular> AND <Hypertension...
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080       <Pneumonia> AND <Cytomegalovirus Infections>
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713                             <Synovitis> AND <Hand>
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251                <Adhesives> AND <Denture Retention>
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161                <Dental Cements> AND <Orthodontics>
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437              <Enteral Nutrition>/<instrumentation>
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442                    <Arthroscopy> AND <Wrist Joint>
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087         <Wheelchairs> AND <Equipment and Supplies>
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776                               <Glomerulonephritis>
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522                                  <Marfan Syndrome>

                                                                                               MAPSUBSETID  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026  BOOLEAN_EXPRESSION_STR
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080  BOOLEAN_EXPRESSION_STR
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713  BOOLEAN_EXPRESSION_STR
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251  BOOLEAN_EXPRESSION_STR
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161  BOOLEAN_EXPRESSION_STR
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437  BOOLEAN_EXPRESSION_STR
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442  BOOLEAN_EXPRESSION_STR
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087  BOOLEAN_EXPRESSION_STR
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776  BOOLEAN_EXPRESSION_STR
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522  BOOLEAN_EXPRESSION_STR

                                                                                    MAPRANK  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026      NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080      NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713      NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251      NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161      NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437      NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442      NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087      NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776      NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522      NaN

                                                                                    MAPVSAB  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026      NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080      NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713      NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251      NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161      NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437      NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442      NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087      NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776      NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522      NaN

                                                                                    MAPATN  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026     NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080     NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713     NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251     NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161     NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437     NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442     NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087     NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776     NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522     NaN

                                                                                    MAPATV  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026     NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080     NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713     NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251     NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161     NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437     NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442     NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087     NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776     NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522     NaN

                                                                                   MAPIN_ID  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026      ATX
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080      ATX
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713      ATX
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251      ATX
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161      ATX
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437      ATX
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442      ATX
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087      ATX
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776      ATX
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522      ATX

                                                                                    MAPIN_TYPE  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026         NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080         NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713         NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251         NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161         NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437         NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442         NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087         NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776         NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522         NaN

                                                                                    MAPOUT_ID  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026        NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080        NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713        NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251        NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161        NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437        NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442        NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087        NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776        NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522        NaN

                                                                                    MAPOUT_TYPE  \
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026          NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080          NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713          NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251          NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161          NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437          NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442          NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087          NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776          NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522          NaN

                                                                                    MAPRULE
C1306694 MTH NaN NaN AT102971857 NaN C0264643 NaN C0264643 CUI NaN NaN SY NaN 3026      NaN
                     AT102971858 NaN C0276253 NaN C0276253 CUI NaN NaN SY NaN 4080      NaN
                     AT102971859 NaN C0409780 NaN C0409780 CUI NaN NaN SY NaN 4713      NaN
                     AT102971861 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 1251      NaN
                     AT102971862 NaN C1706094 NaN C1706094 CUI NaN NaN SY NaN 2161      NaN
                     AT102971863 NaN C0180739 NaN C0180739 CUI NaN NaN RN NaN 2437      NaN
                     AT102971864 NaN C1533661 NaN C1533661 CUI NaN NaN SY NaN 1442      NaN
                     AT110677869 NaN C1962918 NaN C1962918 CUI NaN NaN RN NaN 5087      NaN
                     AT110677871 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 2776      NaN
                     AT110677872 NaN C1855348 NaN C1855348 CUI NaN NaN RU NaN 3522      NaN

Column names (indices) of MRMAP.RRF:
['MAPSETCUI', 'MAPSETSAB', 'MAPSUBSETID', 'MAPRANK', 'MAPVSAB', 'MAPATN', 'MAPATV', 'MAPIN_ID', 'MAPIN_TYPE', 'MAPOUT_ID', 'MAPOUT_TYPE', 'MAPRULE']

## MRSMAP.RRF (Mapping information between terminologies)

MRSMAP.RRF: This file contains information about mappings.  
- **MAPSETCUI**: Map Set Concept Unique Identifier
- **MAPSETSAB**: Map Set Source Abbreviation
- **MAPSUBSETID**: Map Subset ID
- **MAPRANK**: Map Rank
- **MAPVSAB**: Map Versioned Source Abbreviation
- **MAPATN**: Map Attribute Name
- **MAPATV**: Map Attribute Value
- **MAPIN_ID**: Map Input ID
- **MAPIN_TYPE**: Map Input Type
- **MAPOUT_ID**: Map Output ID
- **MAPOUT_TYPE**: Map Output Type
- **MAPRULE**: Mapping Rule

In [42]:
file_path_mrsmap = '/content/drive/MyDrive/UMLS/2025RRFs/MRSMAP.RRF'
df_mrsmap = read_rrf_and_display(file_path_mrsmap, 'MRSMAP.RRF', rrf_column_definitions['MRSMAP.RRF'], nrows=10)

Reading MRSMAP.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRSMAP.RRF
Successfully read MRSMAP.RRF.

First 10 rows of MRSMAP.RRF:

,MAPSETCUI,MAPSETSAB,MAPSUBSETID,MAPRANK,MAPVSAB,MAPATN,MAPATV,MAPIN_ID,MAPIN_TYPE,MAPOUT_ID,MAPOUT_TYPE,MAPRULE
0,C1306694,MTH,AT102971857,NaN,C0264643,CUI,SY,NaN,"<Hypertension, Renovascular> AND <Hypertension...",BOOLEAN_EXPRESSION_STR,NaN,NaN
1,C1306694,MTH,AT102971858,NaN,C0276253,CUI,SY,NaN,<Pneumonia> AND <Cytomegalovirus Infections>,BOOLEAN_EXPRESSION_STR,NaN,NaN
2,C1306694,MTH,AT102971859,NaN,C0409780,CUI,SY,NaN,<Synovitis> AND <Hand>,BOOLEAN_EXPRESSION_STR,NaN,NaN
3,C1306694,MTH,AT102971861,NaN,C1706094,CUI,SY,NaN,<Adhesives> AND <Denture Retention>,BOOLEAN_EXPRESSION_STR,NaN,NaN
4,C1306694,MTH,AT102971862,NaN,C1706094,CUI,SY,NaN,<Dental Cements> AND <Orthodontics>,BOOLEAN_EXPRESSION_STR,NaN,NaN
5,C1306694,MTH,AT102971863,NaN,C0180739,CUI,RN,NaN,<Enteral Nutrition>/<instrumentation>,BOOLEAN_EXPRESSION_STR,NaN,NaN
6,C1306694,MTH,AT102971864,NaN,C1533661,CUI,SY,NaN,<Arthroscopy> AND <Wrist Joint>,BOOLEAN_EXPRESSION_STR,NaN,NaN
7,C1306694,MTH,AT110677869,NaN,C1962918,CUI,RN,NaN,<Wheelchairs> AND <Equipment and Supplies>,BOOLEAN_EXPRESSION_STR,NaN,NaN
8,C1306694,MTH,AT110677871,NaN,C1855348,CUI,RU,NaN,<Glomerulonephritis>,BOOLEAN_EXPRESSION_STR,NaN,NaN
9,C1306694,MTH,AT110677872,NaN,C1855348,CUI,RU,NaN,<Marfan Syndrome>,BOOLEAN_EXPRESSION_STR,NaN,NaN

Column names (indices) of MRSMAP.RRF:
['MAPSETCUI', 'MAPSETSAB', 'MAPSUBSETID', 'MAPRANK', 'MAPVSAB', 'MAPATN', 'MAPATV', 'MAPIN_ID', 'MAPIN_TYPE', 'MAPOUT_ID', 'MAPOUT_TYPE', 'MAPRULE']

## MRXW_ENG.RRF (English extended lexical data)

MRXW_ENG.RRF: This file contains English extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [20]:
file_path_mrsw_eng = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ENG.RRF'
df_mrsw_eng = read_rrf_and_display(file_path_mrsw_eng, 'MRXW_ENG.RRF', rrf_column_definitions['MRXW_ENG.RRF'], nrows=10)

Reading MRXW_ENG.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_ENG.RRF
Successfully read MRXW_ENG.RRF.

First 10 rows of MRXW_ENG.RRF:

     CUI       AUI        STR       LANG  SAB
ENG    1  C5558601  L17380482  S20984470  NaN
ENG  385  C1587222  L10853890  S13501517  NaN
ENG  385  C1587222  L10855615  S13501510  NaN
ENG  385  C1590919  L10855016  S13501511  NaN
ENG  385  C2682874  L10857284  S13501513  NaN
ENG  385  C2682876  L10856721  S13501512  NaN
ENG    4  C5455011  L16947725  S20519531  NaN
ENG    7  C4087078  L13133115  S16091663  NaN
ENG   15  C5849896  L18258298  S22623216  NaN
ENG    1  C5777713  L18645643  S22349131  NaN

Column names (indices) of MRXW_ENG.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXNW_ENG.RRF (English non-hierarchical extended lexical data)

MRXNW_ENG.RRF: This file contains English non-hierarchical extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [23]:
file_path_mrxnw_eng = '/content/drive/MyDrive/UMLS/2025RRFs/MRXNW_ENG.RRF'
df_mrxnw_eng = read_rrf_and_display(file_path_mrxnw_eng, 'MRXNW_ENG.RRF', rrf_column_definitions['MRXNW_ENG.RRF'], nrows=10)

Reading MRXNW_ENG.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXNW_ENG.RRF
Successfully read MRXNW_ENG.RRF.

First 10 rows of MRXNW_ENG.RRF:

     CUI       AUI        STR       LANG  SAB
ENG    1  C5558601  L17380482  S20984470  NaN
ENG  385  C1587222  L10853890  S13501517  NaN
ENG  385  C1587222  L10855615  S13501510  NaN
ENG  385  C1590919  L10855016  S13501511  NaN
ENG  385  C2682874  L10857284  S13501513  NaN
ENG  385  C2682876  L10856721  S13501512  NaN
ENG    4  C5455011  L16947725  S20519531  NaN
ENG    7  C4087078  L13133115  S16091663  NaN
ENG   15  C5849896  L18258298  S22623216  NaN
ENG    1  C5777713  L18645643  S22349131  NaN

Column names (indices) of MRXNW_ENG.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_ARA.RRF (Arabic extended lexical data)

MRXW_ARA.RRF: This file contains Arabic extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [30]:
file_path_mrsw_ara = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ARA.RRF'
df_mrsw_ara = read_rrf_and_display(file_path_mrsw_ara, 'MRXW_ARA.RRF', rrf_column_definitions['MRXW_ARA.RRF'], nrows=10)

Reading MRXW_ARA.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_ARA.RRF
Successfully read MRXW_ARA.RRF.

First 10 rows of MRXW_ARA.RRF:

     CUI       AUI        STR       LANG  SAB
ARA    0  C0154059  L18562632  S22305223  NaN
ARA    0  C0154059  L18572312  S22305229  NaN
ARA    0  C0154060  L18566019  S22332420  NaN
ARA    0  C0154060  L18591324  S22303707  NaN
ARA    0  C0154060  L18620193  S22305337  NaN
ARA    0  C0154060  L18629707  S22303701  NaN
ARA    0  C0154061  L18591311  S22303615  NaN
ARA    0  C0154061  L18601038  S22304554  NaN
ARA    0  C0154062  L18591507  S22305234  NaN
ARA    0  C0154062  L18610421  S22304071  NaN

Column names (indices) of MRXW_ARA.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_BAQ.RRF (Basque extended lexical data)

MRXW_BAQ.RRF: This file contains Basque extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [48]:
file_path_mrsw_baq = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_BAQ.RRF'
df_mrsw_baq = read_rrf_and_display(file_path_mrsw_baq, 'MRXW_BAQ.RRF', rrf_column_definitions['MRXW_BAQ.RRF'], nrows=10)

Reading MRXW_BAQ.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_BAQ.RRF
Successfully read MRXW_BAQ.RRF.

First 10 rows of MRXW_BAQ.RRF:

             CUI       AUI       STR      LANG  SAB
BAQ           30  C0424671  L1521804  S1817713  NaN
BAQ           30  C0497406  L1520973  S1816882  NaN
BAQ           53  C0497111  L1552478  S1848387  NaN
BAQ          a04  C0497294  L1535488  S1831397  NaN
BAQ          a70  C0041327  L1546785  S1842694  NaN
BAQ    abaildura  C0497332  L1547826  S1843735  NaN
BAQ  abdomenaren  C5980104  L1507376  S1803285  NaN
BAQ   abdomeneko  C0497143  L1536808  S1832717  NaN
BAQ      abdomen  C5980104  L1507376  S1803285  NaN
BAQ   abdominala  C0000734  L1529612  S1825521  NaN

Column names (indices) of MRXW_BAQ.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_CHI.RRF (Chinese extended lexical data)

MRXW_CHI.RRF: This file contains Chinese extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [36]:
file_path_mrsw_chi = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_CHI.RRF'
df_mrsw_chi = read_rrf_and_display(file_path_mrsw_chi, 'MRXW_CHI.RRF', rrf_column_definitions['MRXW_CHI.RRF'], nrows=10)

Reading MRXW_CHI.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_CHI.RRF
Successfully read MRXW_CHI.RRF.

First 10 rows of MRXW_CHI.RRF:

            CUI       AUI        STR       LANG  SAB
CHI         000  C5426243  L17138469  S20731769  NaN
CHI         000  C5426255  L17141320  S20732145  NaN
CHI         000  C5453309  L17468496  S21271752  NaN
CHI         000  C5453311  L17494492  S21271687  NaN
CHI         000  C5453313  L17572734  S21272144  NaN
CHI         000  C5889795  L19910282  S23809220  NaN
CHI  000单位胡萝卜素后  C0482467  L19957818  S23811183  NaN
CHI       000美元  C3172569  L12951195  S15824686  NaN
CHI       000美元  C3172570  L12756116  S15824685  NaN
CHI       000美元  C3172572  L12853440  S15824684  NaN

Column names (indices) of MRXW_CHI.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_CZE.RRF (Czech extended lexical data)

MRXW_CZE.RRF: This file contains Czech extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [37]:
file_path_mrsw_cze = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_CZE.RRF'
df_mrsw_cze = read_rrf_and_display(file_path_mrsw_cze, 'MRXW_CZE.RRF', rrf_column_definitions['MRXW_CZE.RRF'], nrows=10)

Reading MRXW_CZE.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_CZE.RRF
Successfully read MRXW_CZE.RRF.

First 10 rows of MRXW_CZE.RRF:

     CUI       AUI       STR       LANG  SAB
CZE    0  C0158855  L8030807  S10088022  NaN
CZE    0  C0158859  L8060782  S10088026  NaN
CZE    0  C0158866  L8023295  S10088033  NaN
CZE    0  C0158870  L8060784  S10088037  NaN
CZE    0  C0158876  L8063479  S10109313  NaN
CZE    0  C0158880  L8055846  S10109317  NaN
CZE    0  C0158886  L8034472  S10116929  NaN
CZE    0  C0158886  L8198369  S10282352  NaN
CZE    0  C0158890  L8049246  S10116933  NaN
CZE    0  C0158890  L8198594  S10282356  NaN

Column names (indices) of MRXW_CZE.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_DAN.RRF (Danish extended lexical data)

MRXW_DAN.RRF: This file contains Danish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [55]:
file_path_mrsw_dan = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_DAN.RRF'
df_mrsw_dan = read_rrf_and_display(file_path_mrsw_dan, 'MRXW_DAN.RRF', rrf_column_definitions['MRXW_DAN.RRF'], nrows=10)

Reading MRXW_DAN.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_DAN.RRF
Successfully read MRXW_DAN.RRF.

First 10 rows of MRXW_DAN.RRF:

               CUI       AUI       STR      LANG  SAB
DAN             30  C0424671  L1252946  S1494892  NaN
DAN             30  C0497406  L1283107  S1525053  NaN
DAN             67  C0497123  L1260632  S1502578  NaN
DAN            a04  C0497294  L1270224  S1512170  NaN
DAN            a70  C0041327  L1306415  S1548361  NaN
DAN        abdomen  C0000734  L1307230  S1549176  NaN
DAN  abdominalbrok  C0740406  L1231876  S1473822  NaN
DAN     abdominale  C0497172  L1228940  S1470886  NaN
DAN      abdominal  C0497175  L1231900  S1473846  NaN
DAN          abdom  C5980104  L1226970  S1468916  NaN

Column names (indices) of MRXW_DAN.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_DUT.RRF (Dutch extended lexical data)

MRXW_DUT.RRF: This file contains Dutch extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [19]:
file_path_mrsw_dut = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_DUT.RRF'
df_mrsw_dut = read_rrf_and_display(file_path_mrsw_dut, 'MRXW_DUT.RRF', rrf_column_definitions['MRXW_DUT.RRF'], nrows=10)

Reading MRXW_DUT.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_DUT.RRF
Successfully read MRXW_DUT.RRF.

First 10 rows of MRXW_DUT.RRF:

     CUI       AUI        STR       LANG  SAB
DUT    0  C0158855   L4991110   S5678614  NaN
DUT    0  C0158859   L4991114   S5678618  NaN
DUT    0  C0158866   L4991099   S5678603  NaN
DUT    0  C0158870   L4991103   S5678607  NaN
DUT    0  C0158876   L4975849   S5663352  NaN
DUT    0  C0158880   L4975853   S5663356  NaN
DUT    0  C0158908   L4961393   S5648897  NaN
DUT    0  C0158912   L4961397   S5648901  NaN
DUT    1  C3699784  L14473953  S17561008  NaN
DUT    1  C3699784  L19172882  S22981636  NaN

Column names (indices) of MRXW_DUT.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_EST.RRF (Estonian extended lexical data)

MRXW_EST.RRF: This file contains Estonian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [39]:
file_path_mrsw_est = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_EST.RRF'
df_mrsw_est = read_rrf_and_display(file_path_mrsw_est, 'MRXW_EST.RRF', rrf_column_definitions['MRXW_EST.RRF'], nrows=10)

Reading MRXW_EST.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_EST.RRF
Successfully read MRXW_EST.RRF.

First 10 rows of MRXW_EST.RRF:

     CUI       AUI        STR       LANG  SAB
EST  102  C2598947  L13580389  S16557990  NaN
EST  201  C2735379  L13517400  S16558027  NaN
EST  301  C2923245  L13580391  S16557999  NaN
EST  302  C2923247  L13532947  S16558036  NaN
EST  501  C2735378  L13517397  S16558008  NaN
EST  602  C3172624  L13580394  S16558045  NaN
EST    0  C0154059  L18913263  S22716628  NaN
EST    0  C0154059  L18936825  S22716463  NaN
EST    0  C0154059  L18949102  S22721148  NaN
EST    0  C0154059  L18983759  S22716629  NaN

Column names (indices) of MRXW_EST.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_FIN.RRF (Finnish extended lexical data)

MRXW_FIN.RRF: This file contains Finnish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [26]:
file_path_mrsw_fin = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_FIN.RRF'
df_mrsw_fin = read_rrf_and_display(file_path_mrsw_fin, 'MRXW_FIN.RRF', rrf_column_definitions['MRXW_FIN.RRF'], nrows=10)

Reading MRXW_FIN.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_FIN.RRF
Successfully read MRXW_FIN.RRF.

First 10 rows of MRXW_FIN.RRF:

     CUI       AUI        STR       LANG  SAB
FIN    0  C0154059  L19066077  S22842732  NaN
FIN    0  C0154059  L19066095  S22842817  NaN
FIN    0  C0154059  L19075076  S22842830  NaN
FIN    0  C0154060  L19075063  S22842721  NaN
FIN    0  C0154060  L19093081  S22842730  NaN
FIN    0  C0154060  L19120165  S22842719  NaN
FIN    0  C0154061  L19093078  S22842711  NaN
FIN    0  C0154061  L19129191  S22842712  NaN
FIN    0  C0154062  L19120171  S22842796  NaN
FIN    0  C0154062  L19129203  S22842797  NaN

Column names (indices) of MRXW_FIN.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_FRE.RRF (French extended lexical data)

MRXW_FRE.RRF: This file contains French extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [25]:
file_path_mrsw_fre = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_FRE.RRF'
df_mrsw_fre = read_rrf_and_display(file_path_mrsw_fre, 'MRXW_FRE.RRF', rrf_column_definitions['MRXW_FRE.RRF'], nrows=10)

Reading MRXW_FRE.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_FRE.RRF
Successfully read MRXW_FRE.RRF.

First 10 rows of MRXW_FRE.RRF:

     CUI       AUI        STR       LANG  SAB
FRE   12  C1681886  L13059206  S16006610  NaN
FRE    0  C0086844  L10290302  S12846164  NaN
FRE    0  C0086844  L10291772  S12846166  NaN
FRE    0  C0158855   L6152443   S7066420  NaN
FRE    0  C0158859   L6142735   S7066424  NaN
FRE    0  C0158866   L6171889   S7066409  NaN
FRE    0  C0158870   L6176698   S7066413  NaN
FRE    0  C0158876   L6177875   S7075725  NaN
FRE    0  C0158880   L6168203   S7075729  NaN
FRE    0  C0158886   L6173862   S7081921  NaN

Column names (indices) of MRXW_FRE.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_GER.RRF (German extended lexical data)

MRXW_GER.RRF: This file contains German extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [47]:
file_path_mrsw_ger = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_GER.RRF'
df_mrsw_ger = read_rrf_and_display(file_path_mrsw_ger, 'MRXW_GER.RRF', rrf_column_definitions['MRXW_GER.RRF'], nrows=10)

Reading MRXW_GER.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_GER.RRF
Successfully read MRXW_GER.RRF.

First 10 rows of MRXW_GER.RRF:

       CUI       AUI        STR       LANG  SAB
GER  00012  C1681886  L13068228  S16006611  NaN
GER  00012  C1681886  L13077327  S16006608  NaN
GER    000  C0057146   L5699259   S6532295  NaN
GER    000  C0071316   L8590006  S10688065  NaN
GER    000  C0071316   L8591399  S10687725  NaN
GER    000  C0071316   L8591958  S10688066  NaN
GER    000  C0158880   L5961935   S6844365  NaN
GER   001a  C0174381   L8589577  S10688411  NaN
GER   001a  C0752214   L8590538  S10688416  NaN
GER   001a  C0905617   L8590838  S10686933  NaN

Column names (indices) of MRXW_GER.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_GRE.RRF (Greek extended lexical data)

MRXW_GRE.RRF: This file contains Greek extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [57]:
file_path_mrsw_gre = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_GRE.RRF'
df_mrsw_gre = read_rrf_and_display(file_path_mrsw_gre, 'MRXW_GRE.RRF', rrf_column_definitions['MRXW_GRE.RRF'], nrows=10)

Reading MRXW_GRE.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_GRE.RRF
Successfully read MRXW_GRE.RRF.

First 10 rows of MRXW_GRE.RRF:

     CUI       AUI        STR       LANG  SAB
GRE    0  C0158855  L18517768  S22202252  NaN
GRE    0  C0158859  L18418922  S22202256  NaN
GRE    0  C0158866  L18399190  S22202241  NaN
GRE    0  C0158870  L18498006  S22202245  NaN
GRE    0  C0158876  L18536842  S22194913  NaN
GRE    0  C0158880  L18516856  S22194917  NaN
GRE    0  C0158886  L18418013  S22194794  NaN
GRE    0  C0158890  L18516840  S22194798  NaN
GRE    0  C0158898  L18501365  S22229181  NaN
GRE    0  C0158902  L18441927  S22229185  NaN

Column names (indices) of MRXW_GRE.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_HEB.RRF (Hebrew extended lexical data)

MRXW_HEB.RRF: This file contains Hebrew extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [38]:
file_path_mrsw_heb = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_HEB.RRF'
df_mrsw_heb = read_rrf_and_display(file_path_mrsw_heb, 'MRXW_HEB.RRF', rrf_column_definitions['MRXW_HEB.RRF'], nrows=10)

Reading MRXW_HEB.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_HEB.RRF
Successfully read MRXW_HEB.RRF.

First 10 rows of MRXW_HEB.RRF:

            CUI       AUI       STR      LANG  SAB
HEB           2  C0233315  L1558577  S1854486  NaN
HEB           5  C0233315  L1558577  S1854486  NaN
HEB    abaabuot  C0008049  L1550048  S1845957  NaN
HEB  abdominali  C0740406  L1551602  S1847511  NaN
HEB      abtzes  C0157680  L1550058  S1845967  NaN
HEB      abtzes  C0497197  L1553434  S1849343  NaN
HEB      abtzes  C0497350  L1550057  S1845966  NaN
HEB       acute  C0497306  L1552030  S1847939  NaN
HEB      ademet  C0035920  L1550063  S1845972  NaN
HEB       aduma  C0235267  L1550235  S1846144  NaN

Column names (indices) of MRXW_HEB.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_HUN.RRF (Hungarian extended lexical data)

MRXW_HUN.RRF: This file contains Hungarian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [41]:
file_path_mrsw_hun = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_HUN.RRF'
df_mrsw_hun = read_rrf_and_display(file_path_mrsw_hun, 'MRXW_HUN.RRF', rrf_column_definitions['MRXW_HUN.RRF'], nrows=10)

Reading MRXW_HUN.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_HUN.RRF
Successfully read MRXW_HUN.RRF.

First 10 rows of MRXW_HUN.RRF:

     CUI       AUI        STR       LANG  SAB
HUN    0  C0154059  L10004550  S12552014  NaN
HUN    0  C0154059  L10021491  S12552046  NaN
HUN    0  C0154059  L10030189  S12552010  NaN
HUN    0  C0154059  L10030190  S12552013  NaN
HUN    0  C0154059  L10063733  S12549407  NaN
HUN    0  C0154060  L10002101  S12531833  NaN
HUN    0  C0154060  L10019000  S12531789  NaN
HUN    0  C0154060  L10036152  S12531904  NaN
HUN    0  C0154060  L10061463  S12531752  NaN
HUN    0  C0154060  L10061497  S12531977  NaN

Column names (indices) of MRXW_HUN.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_ISL.RRF (Icelandic extended lexical data)

MRXW_ISL.RRF: This file contains Icelandic extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [54]:
file_path_mrsw_isl = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ISL.RRF'
df_mrsw_isl = read_rrf_and_display(file_path_mrsw_isl, 'MRXW_ISL.RRF', rrf_column_definitions['MRXW_ISL.RRF'], nrows=10)

Reading MRXW_ISL.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_ISL.RRF
Successfully read MRXW_ISL.RRF.

First 10 rows of MRXW_ISL.RRF:

     CUI       AUI        STR       LANG  SAB
ISL    0  C0158855  L19759828  S23563108  NaN
ISL    0  C0158859  L19783177  S23563112  NaN
ISL    0  C0158866  L19724860  S23563097  NaN
ISL    0  C0158870  L19794784  S23563101  NaN
ISL    0  C0158876  L19721959  S23540489  NaN
ISL    0  C0158880  L19780300  S23540493  NaN
ISL    0  C0158886  L19756925  S23540502  NaN
ISL    0  C0158890  L19780302  S23540506  NaN
ISL    0  C0158898  L19787475  S23597344  NaN
ISL    0  C0158902  L19729202  S23597348  NaN

Column names (indices) of MRXW_ISL.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_ITA.RRF (Italian extended lexical data)

MRXW_ITA.RRF: This file contains Italian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [22]:
file_path_mrsw_ita = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_ITA.RRF'
df_mrsw_ita = read_rrf_and_display(file_path_mrsw_ita, 'MRXW_ITA.RRF', rrf_column_definitions['MRXW_ITA.RRF'], nrows=10)

Reading MRXW_ITA.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_ITA.RRF
Successfully read MRXW_ITA.RRF.

First 10 rows of MRXW_ITA.RRF:

       CUI       AUI        STR       LANG  SAB
ITA  00012  C1681886  L13728424  S16744369  NaN
ITA  00012  C1681886  L13737278  S16744370  NaN
ITA   000g  C5889795  L19897271  S23706396  NaN
ITA    000  C3172569  L16542109  S20042972  NaN
ITA    000  C3172570  L16536008  S20042971  NaN
ITA    000  C3172572  L16539064  S20042970  NaN
ITA    000  C3172573  L16545082  S20042973  NaN
ITA    000  C4036506  L19604518  S23376473  NaN
ITA    000  C5426243  L17142862  S20722580  NaN
ITA    000  C5426255  L17144774  S20716426  NaN

Column names (indices) of MRXW_ITA.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_JPN.RRF (Japanese extended lexical data)

MRXW_JPN.RRF: This file contains Japanese extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [58]:
file_path_mrsw_jpn = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_JPN.RRF'
df_mrsw_jpn = read_rrf_and_display(file_path_mrsw_jpn, 'MRXW_JPN.RRF', rrf_column_definitions['MRXW_JPN.RRF'], nrows=10)

Reading MRXW_JPN.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_JPN.RRF
Successfully read MRXW_JPN.RRF.

First 10 rows of MRXW_JPN.RRF:

          CUI       AUI        STR       LANG  SAB
JPN         0  C0949692   L5446270   S6231326  NaN
JPN       100  C0205666   L7994478  S10039209  NaN
JPN       100  C0205666   L7998758  S10039193  NaN
JPN       100  C0205666   L8015780  S10039182  NaN
JPN    100受容体  C0034821   L3442775   S3970269  NaN
JPN    100歳以上  C0001795  L12081818  S14980893  NaN
JPN  100歳以上の人  C0001795   L3437364   S3964858  NaN
JPN    100蛋白質  C0027758   L5437983   S6223039  NaN
JPN      107b  C0125272  L10105338  S12633377  NaN
JPN        10  C0000641   L3437697   S3965191  NaN

Column names (indices) of MRXW_JPN.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_KOR.RRF (Korean extended lexical data)

MRXW_KOR.RRF: This file contains Korean extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [24]:
file_path_mrsw_kor = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_KOR.RRF'
df_mrsw_kor = read_rrf_and_display(file_path_mrsw_kor, 'MRXW_KOR.RRF', rrf_column_definitions['MRXW_KOR.RRF'], nrows=10)

Reading MRXW_KOR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_KOR.RRF
Successfully read MRXW_KOR.RRF.

First 10 rows of MRXW_KOR.RRF:

     CUI       AUI        STR       LANG  SAB
KOR    0  C0158855  L16090109  S19466228  NaN
KOR    0  C0158859  L16121674  S19466232  NaN
KOR    0  C0158866  L16069155  S19466238  NaN
KOR    0  C0158870  L16090112  S19466242  NaN
KOR    0  C0158876  L16141563  S19456614  NaN
KOR    0  C0158880  L16078467  S19456618  NaN
KOR    0  C0158886  L16128584  S19436941  NaN
KOR    0  C0158890  L16139132  S19436945  NaN
KOR    0  C0158898  L16073587  S19417549  NaN
KOR    0  C0158902  L16105105  S19417553  NaN

Column names (indices) of MRXW_KOR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_LAV.RRF (Latvian extended lexical data)

MRXW_LAV.RRF: This file contains Latvian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [44]:
file_path_mrsw_lav = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_LAV.RRF'
df_mrsw_lav = read_rrf_and_display(file_path_mrsw_lav, 'MRXW_LAV.RRF', rrf_column_definitions['MRXW_LAV.RRF'], nrows=10)

Reading MRXW_LAV.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_LAV.RRF
Successfully read MRXW_LAV.RRF.

First 10 rows of MRXW_LAV.RRF:

     CUI       AUI        STR       LANG  SAB
LAV    0  C0154059  L18110747  S21678412  NaN
LAV    0  C0154059  L18124116  S21678413  NaN
LAV    0  C0154059  L18137113  S21678445  NaN
LAV    0  C0154060  L18070655  S21678433  NaN
LAV    0  C0154060  L18083901  S21678432  NaN
LAV    0  C0154060  L18137109  S21678431  NaN
LAV    0  C0154061  L17919047  S21512258  NaN
LAV    0  C0154061  L18124123  S21678435  NaN
LAV    0  C0154062  L18110748  S21678464  NaN
LAV    0  C0154062  L18124130  S21678465  NaN

Column names (indices) of MRXW_LAV.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_LIT.RRF (Lithuanian extended lexical data)

MRXW_LIT.RRF: This file contains Lithuanian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [29]:
file_path_mrsw_lit = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_LIT.RRF'
df_mrsw_lit = read_rrf_and_display(file_path_mrsw_lit, 'MRXW_LIT.RRF', rrf_column_definitions['MRXW_LIT.RRF'], nrows=10)

Reading MRXW_LIT.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_LIT.RRF
Successfully read MRXW_LIT.RRF.

First 10 rows of MRXW_LIT.RRF:

     CUI       AUI        STR       LANG  SAB
LIT    0  C0158855  L19410533  S23251609  NaN
LIT    0  C0158859  L19531437  S23251613  NaN
LIT    0  C0158866  L19410529  S23251598  NaN
LIT    0  C0158870  L19410530  S23251602  NaN
LIT    0  C0158876  L19497308  S23300562  NaN
LIT    0  C0158880  L19396386  S23300566  NaN
LIT    0  C0158886  L19436812  S23300471  NaN
LIT    0  C0158890  L19456964  S23300475  NaN
LIT    0  C0158898  L19424912  S23206338  NaN
LIT    0  C0158902  L19445259  S23206342  NaN

Column names (indices) of MRXW_LIT.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_NOR.RRF (Norwegian extended lexical data)

MRXW_NOR.RRF: This file contains Norwegian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [27]:
file_path_mrsw_nor = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_NOR.RRF'
df_mrsw_nor = read_rrf_and_display(file_path_mrsw_nor, 'MRXW_NOR.RRF', rrf_column_definitions['MRXW_NOR.RRF'], nrows=10)

Reading MRXW_NOR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_NOR.RRF
Successfully read MRXW_NOR.RRF.

First 10 rows of MRXW_NOR.RRF:

     CUI       AUI        STR       LANG  SAB
NOR    0  C0006107   L1259229   S1501175  NaN
NOR    0  C0009806   L1303406   S1545352  NaN
NOR    0  C0011124   L1258517   S1500463  NaN
NOR    0  C0018437  L10982562  S13676619  NaN
NOR    0  C0018437  L10983172  S13681517  NaN
NOR    0  C0018437  L10992871  S13681514  NaN
NOR    0  C0019209   L1252423   S1494369  NaN
NOR    0  C0024964  L10999457  S13682185  NaN
NOR    0  C0035309   L1227592   S1469538  NaN
NOR    0  C0152149   L1263109   S1505055  NaN

Column names (indices) of MRXW_NOR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_POL.RRF (Polish extended lexical data)

MRXW_POL.RRF: This file contains Polish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [52]:
file_path_mrsw_pol = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_POL.RRF'
df_mrsw_pol = read_rrf_and_display(file_path_mrsw_pol, 'MRXW_POL.RRF', rrf_column_definitions['MRXW_POL.RRF'], nrows=10)

Reading MRXW_POL.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_POL.RRF
Successfully read MRXW_POL.RRF.

First 10 rows of MRXW_POL.RRF:

     CUI       AUI        STR       LANG  SAB
POL    5  C0550528  L18845632  S22606096  NaN
POL    0  C0799330  L20225336  S24076220  NaN
POL    0  C0799331  L20236059  S24076238  NaN
POL    0  C0799332  L20219999  S24076264  NaN
POL    0  C0799333  L20230641  S24076273  NaN
POL    0  C0799334  L20241494  S24076296  NaN
POL    0  C0799335  L20230643  S24076304  NaN
POL    0  C0804016  L20231385  S24082191  NaN
POL    0  C0804020  L20226024  S24082130  NaN
POL    0  C1716198  L20236776  S24082105  NaN

Column names (indices) of MRXW_POL.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_POR.RRF (Portuguese extended lexical data)

MRXW_POR.RRF: This file contains Portuguese extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [51]:
file_path_mrsw_por = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_POR.RRF'
df_mrsw_por = read_rrf_and_display(file_path_mrsw_por, 'MRXW_POR.RRF', rrf_column_definitions['MRXW_POR.RRF'], nrows=10)

Reading MRXW_POR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_POR.RRF
Successfully read MRXW_POR.RRF.

First 10 rows of MRXW_POR.RRF:

     CUI       AUI        STR       LANG  SAB
POR    0  C0158855  L16595919  S20065011  NaN
POR    0  C0158855   L4875582   S5563085  NaN
POR    0  C0158859  L16588751  S20065015  NaN
POR    0  C0158859   L4875586   S5563089  NaN
POR    0  C0158866  L16603118  S20065000  NaN
POR    0  C0158866   L4875571   S5563074  NaN
POR    0  C0158870  L16588746  S20065004  NaN
POR    0  C0158870   L4875575   S5563078  NaN
POR    0  C0158876  L16585178  S20093962  NaN
POR    0  C0158876   L4898458   S5585960  NaN

Column names (indices) of MRXW_POR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_RUS.RRF (Russian extended lexical data)

MRXW_RUS.RRF: This file contains Russian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [46]:
file_path_mrsw_rus = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_RUS.RRF'
df_mrsw_rus = read_rrf_and_display(file_path_mrsw_rus, 'MRXW_RUS.RRF', rrf_column_definitions['MRXW_RUS.RRF'], nrows=10)

Reading MRXW_RUS.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_RUS.RRF
Successfully read MRXW_RUS.RRF.

First 10 rows of MRXW_RUS.RRF:

     CUI       AUI        STR       LANG  SAB
RUS    1  C3699784  L13550741  S16575171  NaN
RUS    2  C3699782  L13566599  S16575177  NaN
RUS    4  C3699780  L13582613  S16575183  NaN
RUS    5  C0550528  L12947425  S15794500  NaN
RUS    5  C3699778  L13550745  S16575189  NaN
RUS    6  C3699776  L13566603  S16575195  NaN
RUS    7  C1961039  L13064998  S16004641  NaN
RUS    7  C3699537  L13519558  S16575201  NaN
RUS    8  C3699535  L13598498  S16575207  NaN
RUS    9  C3699533  L13550746  S16575213  NaN

Column names (indices) of MRXW_RUS.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_SCR.RRF (Croatian/Serbian extended lexical data)

MRXW_SCR.RRF: This file contains Croatian/Serbian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [56]:
file_path_mrsw_scr = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SCR.RRF'
df_mrsw_scr = read_rrf_and_display(file_path_mrsw_scr, 'MRXW_SCR.RRF', rrf_column_definitions['MRXW_SCR.RRF'], nrows=10)

Reading MRXW_SCR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_SCR.RRF
Successfully read MRXW_SCR.RRF.

First 10 rows of MRXW_SCR.RRF:

     CUI       AUI        STR       LANG  SAB
SCR    0  C0154059  L19393614  S23277253  NaN
SCR    0  C0154059  L19393615  S23277254  NaN
SCR    0  C0154059  L19412886  S23269932  NaN
SCR    0  C0154059  L19493441  S23269930  NaN
SCR    0  C0154060  L19433040  S23270390  NaN
SCR    0  C0154060  L19508068  S23225653  NaN
SCR    0  C0154061  L19412854  S23269735  NaN
SCR    0  C0154062  L19513565  S23270143  NaN
SCR    0  C0154062  L19513846  S23272268  NaN
SCR    0  C0154064  L19459479  S23159264  NaN

Column names (indices) of MRXW_SCR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_SPA.RRF (Spanish extended lexical data)

MRXW_SPA.RRF: This file contains Spanish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [35]:
file_path_mrsw_spa = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SPA.RRF'
df_mrsw_spa = read_rrf_and_display(file_path_mrsw_spa, 'MRXW_SPA.RRF', rrf_column_definitions['MRXW_SPA.RRF'], nrows=10)

Reading MRXW_SPA.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_SPA.RRF
Successfully read MRXW_SPA.RRF.

First 10 rows of MRXW_SPA.RRF:

       CUI       AUI        STR       LANG  SAB
SPA  00043  C1298419   L4229738   S4913206  NaN
SPA  00043  C1298419   L4229739   S4913205  NaN
SPA  00043  C4517384  L14314907  S17403730  NaN
SPA  00043  C4517384  L14330001  S17403731  NaN
SPA   0005  C0590157  L14317834  S17426413  NaN
SPA   0005  C0590157  L14340566  S17409351  NaN
SPA   0005  C0590157  L14347657  S17426412  NaN
SPA   0005  C0590157  L14749671  S17954511  NaN
SPA   0005  C0590157  L14770361  S17954510  NaN
SPA  000ui  C1444965   L5411798   S6195149  NaN

Column names (indices) of MRXW_SPA.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_SWE.RRF (Swedish extended lexical data)

MRXW_SWE.RRF: This file contains Swedish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [21]:
file_path_mrsw_swe = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_SWE.RRF'
df_mrsw_swe = read_rrf_and_display(file_path_mrsw_swe, 'MRXW_SWE.RRF', rrf_column_definitions['MRXW_SWE.RRF'], nrows=10)

Reading MRXW_SWE.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_SWE.RRF
Successfully read MRXW_SWE.RRF.

First 10 rows of MRXW_SWE.RRF:

     CUI       AUI        STR       LANG  SAB
SWE    0  C0158855  L18117170  S21730101  NaN
SWE    0  C0158859  L18063874  S21730105  NaN
SWE    0  C0158866  L18117165  S21730090  NaN
SWE    0  C0158870  L18143558  S21730094  NaN
SWE    0  C0158876  L18069414  S21774545  NaN
SWE    0  C0158880  L18082635  S21774549  NaN
SWE    0  C0158886  L18088490  S21714837  NaN
SWE    0  C0158890  L18101909  S21714842  NaN
SWE    0  C0158898  L18100561  S21704153  NaN
SWE    0  C0158902  L18113967  S21704157  NaN

Column names (indices) of MRXW_SWE.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_TUR.RRF (Turkish extended lexical data)

MRXW_TUR.RRF: This file contains Turkish extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [40]:
file_path_mrsw_tur = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_TUR.RRF'
df_mrsw_tur = read_rrf_and_display(file_path_mrsw_tur, 'MRXW_TUR.RRF', rrf_column_definitions['MRXW_TUR.RRF'], nrows=10)

Reading MRXW_TUR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_TUR.RRF
Successfully read MRXW_TUR.RRF.

First 10 rows of MRXW_TUR.RRF:

     CUI       AUI        STR       LANG  SAB
TUR    1  C3699784  L13598491  S16575168  NaN
TUR    2  C3699782  L13629980  S16575174  NaN
TUR    4  C3699780  L13550743  S16575180  NaN
TUR    5  C0550528  L12246792  S15646763  NaN
TUR    5  C3699778  L13519557  S16575186  NaN
TUR    6  C3699776  L13566601  S16575192  NaN
TUR    7  C3699537  L13598496  S16575198  NaN
TUR    8  C3699535  L13566605  S16575204  NaN
TUR    9  C3699533  L13614129  S16575210  NaN
TUR    0  C0799330  L12308388  S15360334  NaN

Column names (indices) of MRXW_TUR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## MRXW_UKR.RRF (Ukrainian extended lexical data)

MRXW_UKR.RRF: This file contains Ukrainian extended attribute values.  
- **CUI**: Concept Unique Identifier
- **AUI**: Atom Unique Identifier
- **STR**: String
- **LANG**: Language
- **SAB**: Source Abbreviation

In [31]:
file_path_mrsw_ukr = '/content/drive/MyDrive/UMLS/2025RRFs/MRXW_UKR.RRF'
df_mrsw_ukr = read_rrf_and_display(file_path_mrsw_ukr, 'MRXW_UKR.RRF', rrf_column_definitions['MRXW_UKR.RRF'], nrows=10)

Reading MRXW_UKR.RRF from: /content/drive/MyDrive/UMLS/2025RRFs/MRXW_UKR.RRF
Successfully read MRXW_UKR.RRF.

First 10 rows of MRXW_UKR.RRF:

     CUI       AUI        STR       LANG  SAB
UKR    5  C0550528  L18230963  S21928488  NaN
UKR    5  C0550528  L18235779  S21928486  NaN
UKR    5  C0550528  L18235791  S21928547  NaN
UKR    5  C0550528  L18245625  S21928545  NaN
UKR    1  C1507892  L18235750  S21928288  NaN
UKR    1  C1507892  L18245574  S21928164  NaN
UKR    1  C1507892  L18245595  S21928291  NaN
UKR    1  C1507892  L18247953  S21928298  NaN
UKR    5  C0550529  L18230964  S21928489  NaN
UKR    5  C0550529  L18235790  S21928546  NaN

Column names (indices) of MRXW_UKR.RRF:
['CUI', 'AUI', 'STR', 'LANG', 'SAB']

## Verification of RRF File Processing

Let's verify that all RRF files defined in `rrf_column_definitions` have been processed and displayed, and that no duplicates remain.

In [96]:
expected_rrf_files = list(rrf_column_definitions.keys())
print(f"Expected RRF files ({len(expected_rrf_files)}):\n{sorted(expected_rrf_files)}")

Expected RRF files (48):
['AMBIGLUI.RRF', 'AMBIGSUI.RRF', 'MRAUI.RRF', 'MRCOLS.RRF', 'MRCONSO.RRF', 'MRCUI.RRF', 'MRDEF.RRF', 'MRDOC.RRF', 'MRFILES.RRF', 'MRHIER.RRF', 'MRMAP.RRF', 'MRRANK.RRF', 'MRREL.RRF', 'MRSAB.RRF', 'MRSAT.RRF', 'MRSMAP.RRF', 'MRSTY.RRF', 'MRXNS_ENG.RRF', 'MRXNW_ENG.RRF', 'MRXW_ARA.RRF', 'MRXW_BAQ.RRF', 'MRXW_CHI.RRF', 'MRXW_CZE.RRF', 'MRXW_DAN.RRF', 'MRXW_DUT.RRF', 'MRXW_ENG.RRF', 'MRXW_EST.RRF', 'MRXW_FIN.RRF', 'MRXW_FRE.RRF', 'MRXW_GER.RRF', 'MRXW_GRE.RRF', 'MRXW_HEB.RRF', 'MRXW_HUN.RRF', 'MRXW_ISL.RRF', 'MRXW_ITA.RRF', 'MRXW_JPN.RRF', 'MRXW_KOR.RRF', 'MRXW_LAV.RRF', 'MRXW_LIT.RRF', 'MRXW_NOR.RRF', 'MRXW_POL.RRF', 'MRXW_POR.RRF', 'MRXW_RUS.RRF', 'MRXW_SCR.RRF', 'MRXW_SPA.RRF', 'MRXW_SWE.RRF', 'MRXW_TUR.RRF', 'MRXW_UKR.RRF']

In [95]:
import sys

processed_dataframes = []
for var_name, var_obj in list(sys.modules[__name__].__dict__.items()):
    if var_name.startswith('df_') and isinstance(var_obj, pd.DataFrame):
        # Extract the original RRF file name from the variable name
        # e.g., 'df_ambiglui' -> 'AMBIGLUI.RRF'
        # This assumes a consistent naming convention `df_lower_case_rrf_name`
        rrf_name_part = var_name[len('df_'):].upper() + '.RRF'

        # Correct the naming inconsistency for MRXW_ files by replacing MRSW_ with MRXW_
        if rrf_name_part.startswith('MRSW_'):
            rrf_name_part = rrf_name_part.replace('MRSW_', 'MRXW_', 1) # Replace only the first occurrence

        processed_dataframes.append(rrf_name_part)


processed_dataframes = sorted(list(set(processed_dataframes))) # Remove potential duplicates and sort

print(f"\nProcessed DataFrames ({len(processed_dataframes)}):\n{processed_dataframes}")

Processed DataFrames (48):
['AMBIGLUI.RRF', 'AMBIGSUI.RRF', 'MRAUI.RRF', 'MRCOLS.RRF', 'MRCONSO.RRF', 'MRCUI.RRF', 'MRDEF.RRF', 'MRDOC.RRF', 'MRFILES.RRF', 'MRHIER.RRF', 'MRMAP.RRF', 'MRRANK.RRF', 'MRREL.RRF', 'MRSAB.RRF', 'MRSAT.RRF', 'MRSMAP.RRF', 'MRSTY.RRF', 'MRXNS_ENG.RRF', 'MRXNW_ENG.RRF', 'MRXW_ARA.RRF', 'MRXW_BAQ.RRF', 'MRXW_CHI.RRF', 'MRXW_CZE.RRF', 'MRXW_DAN.RRF', 'MRXW_DUT.RRF', 'MRXW_ENG.RRF', 'MRXW_EST.RRF', 'MRXW_FIN.RRF', 'MRXW_FRE.RRF', 'MRXW_GER.RRF', 'MRXW_GRE.RRF', 'MRXW_HEB.RRF', 'MRXW_HUN.RRF', 'MRXW_ISL.RRF', 'MRXW_ITA.RRF', 'MRXW_JPN.RRF', 'MRXW_KOR.RRF', 'MRXW_LAV.RRF', 'MRXW_LIT.RRF', 'MRXW_NOR.RRF', 'MRXW_POL.RRF', 'MRXW_POR.RRF', 'MRXW_RUS.RRF', 'MRXW_SCR.RRF', 'MRXW_SPA.RRF', 'MRXW_SWE.RRF', 'MRXW_TUR.RRF', 'MRXW_UKR.RRF']

In [97]:
missing_files = [f for f in expected_rrf_files if f not in processed_dataframes]
extra_dfs = [f for f in processed_dataframes if f not in expected_rrf_files]

if not missing_files:
    print("\n✅ All expected RRF files have a corresponding processed DataFrame.")
else:
    print(f"\n❌ The following RRF files were not processed: {missing_files}")

if not extra_dfs:
    print("✅ No extra DataFrames found that do not correspond to an expected RRF file.")
else:
    print(f"❌ The following DataFrames were processed but not expected: {extra_dfs}")

# Quick check for column names in one of the dataframes (already done for all during previous turns)
# The `read_rrf_and_display` function implicitly verifies column names against `rrf_column_definitions`
# and prints them out. If there were issues, they would have appeared in the previous output cells.

✅ All expected RRF files have a corresponding processed DataFrame.
✅ No extra DataFrames found that do not correspond to an expected RRF file.

# NET Folder

In [107]:
sn_column_definitions = {
    'SRDEF': ['UI', 'DEF', 'EX', 'STY', 'STN', 'RTN', 'SQ', 'RL', 'TUI', 'HV', 'ATN', 'ATV', 'CHG', 'DEFC', 'CVF'],
    'SRFIL': ['FIL', 'DES', 'FMT', 'CLS', 'RWS', 'BTS', 'CRS', 'VER'],
    'SRFLD': ['FLD', 'DES', 'FIL', 'MIN_LEN', 'MAX_LEN', 'DATA_TY', 'CUI_STY', 'ATN_STY', 'RL_STY'],
    'SRSTR': ['STY_UI', 'STY_NAME', 'TREE_NUMBER', 'SG_TYPE', 'PAR_STY_UI', 'CHG'],
    'SRSTRE1': ['CHILD_UI', 'CHILD_NAME', 'PARENT_UI', 'PARENT_NAME', 'REL_TYPE'],
    'SRSTRE2': ['CHILD_UI', 'CHILD_NAME', 'PARENT_UI', 'PARENT_NAME', 'REL_TYPE'],
    'SU': ['SG_ID', 'SG_NAME', 'STY_TUI', 'STY_NAME']
}

# Extend the existing rrf_column_definitions for consistency
rrf_column_definitions.update(sn_column_definitions)

net_files = ['SRDEF', 'SRFIL', 'SRFLD', 'SRSTR', 'SRSTRE1', 'SRSTRE2', 'SU']
net_folder = '/content/drive/MyDrive/UMLS/2025AB/NET'

## SRDEF

SRDEF: This file contains definitions of Semantic Types and their relationships.  
- **UI**: Unique Identifier
- **DEF**: Definition
- **EX**: Example
- **STY**: Semantic Type
- **STN**: Semantic Type Name
- **RTN**: Root Node
- **SQ**: Sequence
- **RL**: Relationship Label
- **TUI**: Tree Unique Identifier
- **HV**: Hierarchical View
- **ATN**: Attribute Name
- **ATV**: Attribute Value
- **CHG**: Change Status
- **DEFC**: Definition Creator
- **CVF**: Content View Flag

In [108]:
file_path_srdef = os.path.join(net_folder, 'SRDEF')
df_srdef = read_rrf_and_display(file_path_srdef, 'SRDEF', rrf_column_definitions['SRDEF'], nrows=10)

Reading SRDEF from: /content/drive/MyDrive/UMLS/2025AB/NET/SRDEF
Successfully read SRDEF.

First 10 rows of SRDEF:

,UI,DEF,EX,STY,STN,RTN,SQ,RL,TUI,HV,ATN,ATV,CHG,DEFC,CVF
0,STY,T001,Organism,A1.1,"Generally, a living individual, including all ...",NaN,NaN,NaN,orgm,NaN,NaN,NaN,NaN,NaN,NaN
1,STY,T002,Plant,A1.1.3.3,"An organism having cellulose cell walls, growi...",NaN,NaN,NaN,plnt,NaN,NaN,NaN,NaN,NaN,NaN
2,STY,T004,Fungus,A1.1.3.2,A eukaryotic organism characterized by the abs...,NaN,NaN,NaN,fngs,NaN,NaN,NaN,NaN,NaN,NaN
3,STY,T005,Virus,A1.1.4,An organism consisting of a core of a single n...,NaN,NaN,NaN,virs,NaN,NaN,NaN,NaN,NaN,NaN
4,STY,T007,Bacterium,A1.1.2,"A small, typically one-celled, prokaryotic mic...",NaN,NaN,NaN,bact,NaN,NaN,NaN,NaN,NaN,NaN
5,STY,T008,Animal,A1.1.3.1,"An organism with eukaryotic cells, and lacking...",NaN,NaN,NaN,anim,NaN,NaN,NaN,NaN,NaN,NaN
6,STY,T010,Vertebrate,A1.1.3.1.1,An animal which has a spinal column.,NaN,Few concepts will be assigned to this broad type.,NaN,vtbt,NaN,NaN,NaN,NaN,NaN,NaN
7,STY,T011,Amphibian,A1.1.3.1.1.1,"A cold-blooded, smooth-skinned vertebrate whic...",NaN,NaN,NaN,amph,NaN,NaN,NaN,NaN,NaN,NaN
8,STY,T012,Bird,A1.1.3.1.1.2,A vertebrate having a constant body temperatur...,NaN,NaN,NaN,bird,NaN,NaN,NaN,NaN,NaN,NaN
9,STY,T013,Fish,A1.1.3.1.1.3,A cold-blooded aquatic vertebrate characterize...,NaN,NaN,NaN,fish,NaN,NaN,NaN,NaN,NaN,NaN

Column names (indices) of SRDEF:
['UI', 'DEF', 'EX', 'STY', 'STN', 'RTN', 'SQ', 'RL', 'TUI', 'HV', 'ATN', 'ATV', 'CHG', 'DEFC', 'CVF']

## SRFIL

SRFIL: This file provides information about the Semantic Network files.  
- **FIL**: File Name
- **DES**: Description
- **FMT**: Format
- **CLS**: Class
- **RWS**: Rows
- **BTS**: Bytes
- **CRS**: Checksum
- **VER**: Version

In [109]:
file_path_srfil = os.path.join(net_folder, 'SRFIL')
df_srfil = read_rrf_and_display(file_path_srfil, 'SRFIL', rrf_column_definitions['SRFIL'], nrows=10)

Reading SRFIL from: /content/drive/MyDrive/UMLS/2025AB/NET/SRFIL
Successfully read SRFIL.

First 10 rows of SRFIL:

,FIL,DES,FMT,CLS,RWS,BTS,CRS,VER
0,SRDEF,Basic information about the Semantic Types and...,"RT,UI,STY/RL,STN/RTN,DEF,EX,UN,NH,ABR,RIN",10,187,44474,NaN,NaN
1,SRFIL,File Description,"FIL,DES,FMT,CLS,RWS,BTS",6,6,435,NaN,NaN
2,SRFLD,Field Description,"COL,DES,REF,FIL",4,21,683,NaN,NaN
3,SRSTRE1,Fully inherited set of Relations (UIs),"UI,UI,UI",3,6704,107264,NaN,NaN
4,SRSTRE2,Fully inherited set of Relations (Names),"STY,RL,STY",3,6704,341866,NaN,NaN
5,SRSTR,Structure of the Network,"STY/RL,RL,STY/RL,LS",4,603,30436,NaN,NaN

Column names (indices) of SRFIL:
['FIL', 'DES', 'FMT', 'CLS', 'RWS', 'BTS', 'CRS', 'VER']

## SRFLD

SRFLD: This file describes the fields (columns) within the Semantic Network files.  
- **FLD**: Field Name
- **DES**: Description
- **FIL**: File
- **MIN_LEN**: Minimum Length
- **MAX_LEN**: Maximum Length
- **DATA_TY**: Data Type
- **CUI_STY**: CUI Semantic Type
- **ATN_STY**: Attribute Name Semantic Type
- **RL_STY**: Relationship Label Semantic Type

In [110]:
file_path_srfld = os.path.join(net_folder, 'SRFLD')
df_srfld = read_rrf_and_display(file_path_srfld, 'SRFLD', rrf_column_definitions['SRFLD'], nrows=10)

Reading SRFLD from: /content/drive/MyDrive/UMLS/2025AB/NET/SRFLD
Successfully read SRFLD.

First 10 rows of SRFLD:

,FLD,DES,FIL,MIN_LEN,MAX_LEN,DATA_TY,CUI_STY,ATN_STY,RL_STY
0,ABR,abbreviation,3.2,SRDEF,NaN,NaN,NaN,NaN,NaN
1,BTS,size in bytes,3.2,SRFIL,NaN,NaN,NaN,NaN,NaN
2,CLS,number of columns,3.2,SRFIL,NaN,NaN,NaN,NaN,NaN
3,COL,field name,3.2,SRFLD,NaN,NaN,NaN,NaN,NaN
4,DEF,definition,3.2,SRDEF,NaN,NaN,NaN,NaN,NaN
5,DES,short description,3.2,"SRFLD,SRFIL",NaN,NaN,NaN,NaN,NaN
6,EX,examples,3.2,SRDEF,NaN,NaN,NaN,NaN,NaN
7,FIL,file name(s),3.2,"SRFLD,SRFIL",NaN,NaN,NaN,NaN,NaN
8,FMT,format,3.2,SRFIL,NaN,NaN,NaN,NaN,NaN
9,LS,link status,3.2,SRSTR,NaN,NaN,NaN,NaN,NaN

Column names (indices) of SRFLD:
['FLD', 'DES', 'FIL', 'MIN_LEN', 'MAX_LEN', 'DATA_TY', 'CUI_STY', 'ATN_STY', 'RL_STY']

## SRSTR

SRSTR: This file contains the string values for semantic types and their attributes.  
- **STY_UI**: Semantic Type Unique Identifier
- **STY_NAME**: Semantic Type Name
- **TREE_NUMBER**: Tree Number
- **SG_TYPE**: Semantic Group Type
- **PAR_STY_UI**: Parent Semantic Type Unique Identifier
- **CHG**: Change Status

In [111]:
file_path_srstr = os.path.join(net_folder, 'SRSTR')
df_srstr = read_rrf_and_display(file_path_srstr, 'SRSTR', rrf_column_definitions['SRSTR'], nrows=10)

Reading SRSTR from: /content/drive/MyDrive/UMLS/2025AB/NET/SRSTR
Successfully read SRSTR.

First 10 rows of SRSTR:

,STY_UI,STY_NAME,TREE_NUMBER,SG_TYPE,PAR_STY_UI,CHG
0,Acquired Abnormality,co-occurs_with,Injury or Poisoning,D,NaN,NaN
1,Acquired Abnormality,isa,Anatomical Abnormality,D,NaN,NaN
2,Acquired Abnormality,result_of,Behavior,D,NaN,NaN
3,Activity,isa,Event,D,NaN,NaN
4,Age Group,isa,Group,D,NaN,NaN
5,Amino Acid Sequence,isa,Molecular Sequence,D,NaN,NaN
6,Amino Acid Sequence,property_of,"Amino Acid, Peptide, or Protein",D,NaN,NaN
7,Amino Acid Sequence,property_of,Gene or Genome,D,NaN,NaN
8,"Amino Acid, Peptide, or Protein",consists_of,"Amino Acid, Peptide, or Protein",D,NaN,NaN
9,"Amino Acid, Peptide, or Protein",isa,Organic Chemical,D,NaN,NaN

Column names (indices) of SRSTR:
['STY_UI', 'STY_NAME', 'TREE_NUMBER', 'SG_TYPE', 'PAR_STY_UI', 'CHG']

## SRSTRE1

SRSTRE1: This file describes hierarchical relationships within the Semantic Network, specifically from children to parents.  
- **CHILD_UI**: Child Unique Identifier
- **CHILD_NAME**: Child Name
- **PARENT_UI**: Parent Unique Identifier
- **PARENT_NAME**: Parent Name
- **REL_TYPE**: Relationship Type

In [112]:
file_path_srstre1 = os.path.join(net_folder, 'SRSTRE1')
df_srstre1 = read_rrf_and_display(file_path_srstre1, 'SRSTRE1', rrf_column_definitions['SRSTRE1'], nrows=10)

Reading SRSTRE1 from: /content/drive/MyDrive/UMLS/2025AB/NET/SRSTRE1
Successfully read SRSTRE1.

First 10 rows of SRSTRE1:

  CHILD_UI CHILD_NAME PARENT_UI  PARENT_NAME  REL_TYPE
0     T001       T142      T001          NaN       NaN
1     T001       T142      T002          NaN       NaN
2     T001       T142      T004          NaN       NaN
3     T001       T142      T005          NaN       NaN
4     T001       T142      T007          NaN       NaN
5     T001       T142      T008          NaN       NaN
6     T001       T142      T010          NaN       NaN
7     T001       T142      T011          NaN       NaN
8     T001       T142      T012          NaN       NaN
9     T001       T142      T013          NaN       NaN

Column names (indices) of SRSTRE1:
['CHILD_UI', 'CHILD_NAME', 'PARENT_UI', 'PARENT_NAME', 'REL_TYPE']

## SRSTRE2

SRSTRE2: This file describes hierarchical relationships within the Semantic Network, specifically from parents to children.  
- **CHILD_UI**: Child Unique Identifier
- **CHILD_NAME**: Child Name
- **PARENT_UI**: Parent Unique Identifier
- **PARENT_NAME**: Parent Name
- **REL_TYPE**: Relationship Type

In [113]:
file_path_srstre2 = os.path.join(net_folder, 'SRSTRE2')
df_srstre2 = read_rrf_and_display(file_path_srstre2, 'SRSTRE2', rrf_column_definitions['SRSTRE2'], nrows=10)

Reading SRSTRE2 from: /content/drive/MyDrive/UMLS/2025AB/NET/SRSTRE2
Successfully read SRSTRE2.

First 10 rows of SRSTRE2:

               CHILD_UI CHILD_NAME         PARENT_UI  PARENT_NAME  REL_TYPE
0  Acquired Abnormality    affects         Amphibian          NaN       NaN
1  Acquired Abnormality    affects            Animal          NaN       NaN
2  Acquired Abnormality    affects          Archaeon          NaN       NaN
3  Acquired Abnormality    affects         Bacterium          NaN       NaN
4  Acquired Abnormality    affects              Bird          NaN       NaN
5  Acquired Abnormality    affects     Cell Function          NaN       NaN
6  Acquired Abnormality    affects         Eukaryote          NaN       NaN
7  Acquired Abnormality    affects              Fish          NaN       NaN
8  Acquired Abnormality    affects            Fungus          NaN       NaN
9  Acquired Abnormality    affects  Genetic Function          NaN       NaN

Column names (indices) of SRSTRE2:
['CHILD_UI', 'CHILD_NAME', 'PARENT_UI', 'PARENT_NAME', 'REL_TYPE']

## SU

SU: This file contains semantic types and their associated information.  
- **SG_ID**: Semantic Group ID
- **SG_NAME**: Semantic Group Name
- **STY_TUI**: Semantic Type Tree Unique Identifier
- **STY_NAME**: Semantic Type Name

In [114]:
file_path_su = os.path.join(net_folder, 'SU')
df_su = read_rrf_and_display(file_path_su, 'SU', rrf_column_definitions['SU'], nrows=10)

Reading SU from: /content/drive/MyDrive/UMLS/2025AB/NET/SU
Successfully read SU.

First 10 rows of SU:

,SG_ID,SG_NAME,STY_TUI,STY_NAME
0,UI: T020,NaN,NaN,NaN
1,STY: Acquired Abnormality,NaN,NaN,NaN
2,ABR: acab,NaN,NaN,NaN
3,STN: A1.2.2.2,NaN,NaN,NaN
4,"DEF: An abnormal structure, or one that is abn...",NaN,NaN,NaN
5,in or deriving from a previously normal struct...,NaN,NaN,NaN
6,distinguished from diseases even though they m...,NaN,NaN,NaN
7,"functioning (e.g., ""hernias incarcerate"").",NaN,NaN,NaN
8,"EX: Hemorrhoids; Hernia, Femoral; Cauliflower ear",NaN,NaN,NaN
9,HL: {isa} Anatomical Abnormality,NaN,NaN,NaN

Column names (indices) of SU:
['SG_ID', 'SG_NAME', 'STY_TUI', 'STY_NAME']

# Generate Summary Table

In [117]:
import pandas as pd
import sys

summary_data = []

# Iterate through all variables in the current global scope
for var_name, var_obj in list(sys.modules[__name__].__dict__.items()):
    # Check if the variable is a pandas DataFrame and its name starts with 'df_'
    if var_name.startswith('df_') and isinstance(var_obj, pd.DataFrame):
        # Extract the base name (e.g., 'mrconso' from 'df_mrconso')
        base_name = var_name[len('df_'):]

        # Determine the original RRF file name
        # Convert to uppercase to match dictionary keys
        uppercased_base_name = base_name.upper()

        if uppercased_base_name + '.RRF' in rrf_column_definitions:
            df_name = uppercased_base_name + '.RRF'
        elif uppercased_base_name in rrf_column_definitions:
            df_name = uppercased_base_name
        else:
            # Handle potential MRSW_ to MRXW_ conversion if not found directly
            if uppercased_base_name.startswith('MRSW_'):
                corrected_name = uppercased_base_name.replace('MRSW_', 'MRXW_', 1)
                if corrected_name + '.RRF' in rrf_column_definitions:
                    df_name = corrected_name + '.RRF'
                elif corrected_name in rrf_column_definitions:
                    df_name = corrected_name
                else:
                    df_name = uppercased_base_name # Fallback if correction doesn't match
            else:
                df_name = uppercased_base_name # Fallback if no specific match

        num_rows = var_obj.shape[0]
        column_names = var_obj.columns.tolist()

        summary_data.append({
            'DataFrame Name': df_name,
            'Number of Rows': num_rows,
            'Column Names': column_names
        })

# Create the summary DataFrame
df_summary = pd.DataFrame(summary_data)

print("Summary of Loaded DataFrames:")
display(df_summary)

Summary of Loaded DataFrames:

,DataFrame Name,Number of Rows,Column Names
0,AMBIGLUI.RRF,10,"[LUI, CUI, VER]"
1,MRCONSO.RRF,10,"[CUI, LAT, TS, LUI, STT, SUI, ISPREF, AUI, SAU..."
2,MRDEF.RRF,10,"[CUI, AUI, ATUI, SATUI, SAB, DEF, SUPPRESS, CV..."
3,MRREL.RRF,10,"[CUI1, AUI1, STYPE1, REL, CUI2, AUI2, STYPE2, ..."
4,MRSTY.RRF,10,"[CUI, TUI, STN, STY, ATUI, CVF]"
5,MRSAB.RRF,10,"[VCUI, RCUI, VSAB, RSAB, SON, SF, SVER, VAB, R..."
6,MRHIER.RRF,10,"[CUI, AUI, CUI_PR, AUI_PR, SAB]"
7,MRXW_DUT.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
8,MRXW_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
9,MRXW_SWE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
10,MRXW_ITA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
11,MRXNW_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
12,MRXW_KOR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
13,MRXW_FRE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
14,MRXW_FIN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
15,MRXW_NOR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
16,MRCOLS.RRF,10,"[COL, COL_NM, FLG, FBG, FBL, DIR_NM, FIL, MIN_..."
17,MRXW_LIT.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
18,MRXW_ARA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
19,MRXW_UKR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
20,AMBIGSUI.RRF,10,"[SUI, CUI, VER]"
21,MRAUI.RRF,10,"[AUI, CUI, LUI, SUI, SAP, VER]"
22,MRSAT.RRF,10,"[CUI, LUI, SUI, AUI, SCUI, SAB, ATN, ATV, SATU..."
23,MRXW_SPA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
24,MRXW_CHI.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
25,MRXW_CZE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
26,MRXW_HEB.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
27,MRXW_EST.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
28,MRXW_TUR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
29,MRXW_HUN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
30,MRSMAP.RRF,10,"[MAPSETCUI, MAPSETSAB, MAPSUBSETID, MAPRANK, M..."
31,MRFILES.RRF,10,"[FIL, DES, FMT, CLS, RWS, BTS, CRS, VER]"
32,MRXW_LAV.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
33,MRMAP.RRF,10,"[MAPSETCUI, MAPSETSAB, MAPSUBSETID, MAPRANK, M..."
34,MRXW_RUS.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
35,MRXW_GER.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
36,MRXW_BAQ.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
37,MRDOC.RRF,10,"[DOCKEY, VALUE, TYPE, EXPL, MIN_LEN, MAX_LEN]"
38,MRCUI.RRF,10,"[CUI1, CUI2, VCUI]"
39,MRXW_POR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
40,MRXW_POL.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
41,MRRANK.RRF,10,"[RANK, MRRANK_COL, MRRANK_FIELD, RANK_TYPE, SU..."
42,MRXW_ISL.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
43,MRXW_DAN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
44,MRXW_SCR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
45,MRXW_GRE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
46,MRXW_JPN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
47,MRXNS_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
48,SRDEF,10,"[UI, DEF, EX, STY, STN, RTN, SQ, RL, TUI, HV, ..."
49,SRFIL,6,"[FIL, DES, FMT, CLS, RWS, BTS, CRS, VER]"
50,SRFLD,10,"[FLD, DES, FIL, MIN_LEN, MAX_LEN, DATA_TY, CUI..."
51,SRSTR,10,"[STY_UI, STY_NAME, TREE_NUMBER, SG_TYPE, PAR_S..."
52,SRSTRE1,10,"[CHILD_UI, CHILD_NAME, PARENT_UI, PARENT_NAME,..."
53,SRSTRE2,10,"[CHILD_UI, CHILD_NAME, PARENT_UI, PARENT_NAME,..."
54,SU,10,"[SG_ID, SG_NAME, STY_TUI, STY_NAME]"
55,SUMMARY,55,"[DataFrame Name, Number of Rows, Column Names]"

# Display Summary Table

In [116]:
display(df_summary)

,DataFrame Name,Number of Rows,Column Names
0,AMBIGLUI.RRF,10,"[LUI, CUI, VER]"
1,MRCONSO.RRF,10,"[CUI, LAT, TS, LUI, STT, SUI, ISPREF, AUI, SAU..."
2,MRDEF.RRF,10,"[CUI, AUI, ATUI, SATUI, SAB, DEF, SUPPRESS, CV..."
3,MRREL.RRF,10,"[CUI1, AUI1, STYPE1, REL, CUI2, AUI2, STYPE2, ..."
4,MRSTY.RRF,10,"[CUI, TUI, STN, STY, ATUI, CVF]"
5,MRSAB.RRF,10,"[VCUI, RCUI, VSAB, RSAB, SON, SF, SVER, VAB, R..."
6,MRHIER.RRF,10,"[CUI, AUI, CUI_PR, AUI_PR, SAB]"
7,MRXW_DUT.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
8,MRXW_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
9,MRXW_SWE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
10,MRXW_ITA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
11,MRXNW_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
12,MRXW_KOR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
13,MRXW_FRE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
14,MRXW_FIN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
15,MRXW_NOR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
16,MRCOLS.RRF,10,"[COL, COL_NM, FLG, FBG, FBL, DIR_NM, FIL, MIN_..."
17,MRXW_LIT.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
18,MRXW_ARA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
19,MRXW_UKR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
20,AMBIGSUI.RRF,10,"[SUI, CUI, VER]"
21,MRAUI.RRF,10,"[AUI, CUI, LUI, SUI, SAP, VER]"
22,MRSAT.RRF,10,"[CUI, LUI, SUI, AUI, SCUI, SAB, ATN, ATV, SATU..."
23,MRXW_SPA.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
24,MRXW_CHI.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
25,MRXW_CZE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
26,MRXW_HEB.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
27,MRXW_EST.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
28,MRXW_TUR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
29,MRXW_HUN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
30,MRSMAP.RRF,10,"[MAPSETCUI, MAPSETSAB, MAPSUBSETID, MAPRANK, M..."
31,MRFILES.RRF,10,"[FIL, DES, FMT, CLS, RWS, BTS, CRS, VER]"
32,MRXW_LAV.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
33,MRMAP.RRF,10,"[MAPSETCUI, MAPSETSAB, MAPSUBSETID, MAPRANK, M..."
34,MRXW_RUS.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
35,MRXW_GER.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
36,MRXW_BAQ.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
37,MRDOC.RRF,10,"[DOCKEY, VALUE, TYPE, EXPL, MIN_LEN, MAX_LEN]"
38,MRCUI.RRF,10,"[CUI1, CUI2, VCUI]"
39,MRXW_POR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
40,MRXW_POL.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
41,MRRANK.RRF,10,"[RANK, MRRANK_COL, MRRANK_FIELD, RANK_TYPE, SU..."
42,MRXW_ISL.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
43,MRXW_DAN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
44,MRXW_SCR.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
45,MRXW_GRE.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
46,MRXW_JPN.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
47,MRXNS_ENG.RRF,10,"[CUI, AUI, STR, LANG, SAB]"
48,SRDEF,10,"[UI, DEF, EX, STY, STN, RTN, SQ, RL, TUI, HV, ..."
49,SRFIL,6,"[FIL, DES, FMT, CLS, RWS, BTS, CRS, VER]"
50,SRFLD,10,"[FLD, DES, FIL, MIN_LEN, MAX_LEN, DATA_TY, CUI..."
51,SRSTR,10,"[STY_UI, STY_NAME, TREE_NUMBER, SG_TYPE, PAR_S..."
52,SRSTRE1,10,"[CHILD_UI, CHILD_NAME, PARENT_UI, PARENT_NAME,..."
53,SRSTRE2,10,"[CHILD_UI, CHILD_NAME, PARENT_UI, PARENT_NAME,..."
54,SU,10,"[SG_ID, SG_NAME, STY_TUI, STY_NAME]"